import { useCallback, useEffect, useMemo, useState, type KeyboardEvent } from 'react'
import iconoBusqueda from '../../../assets/acciones/busqueda.png'
import iconoEditar from '../../../assets/acciones/editar.png'
import iconoVer from '../../../assets/acciones/ver.png'
import { PistaAuditoria, type ConsultaAuditoria } from '../../../shared/auditoria'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { BotonExportar, type FormatoExportacion } from '../../../shared/components/boton-exportar'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { PaginacionTabla, TablaDatos, type ColumnaTabla, type ColumnFiltersState, type SortingState } from '../../../shared/components/tabla-datos'
import { actualizarCajaConfiguracion, configurarPoliticaCaja, crearCajaConfiguracion, exportarCaja, listarAuditoriaCaja, listarCaja, obtenerOpcionesCaja } from '../caja-api'
import { convertirQuetzalesACentavos, etiquetasEstadoCaja, etiquetasTipoCaja, formatearCentavos, formatearFechaHora } from '../caja-formatos'
import type { CajaConfiguracion, EstadoCaja, OpcionesFiltrosCaja, PoliticaCaja, ResultadoPaginado, TipoCaja } from '../caja.types'
import { CajaBreadcrumb } from './caja-breadcrumb'
import styles from './caja.module.css'

type Props = { permisos: readonly string[]; onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }
type CajaEdicion = { id?: string; codigo: string; nombre: string; tipo: TipoCaja; estado: EstadoCaja; motivo: string; version?: number }
type Pestana = 'politica' | 'cajas'
type VistaPolitica = 'listado' | 'detalle' | 'edicion'
type ValoresPolitica = { horaInicio: string; horaFin: string; fondoMaximo: string; saldoMaximo: string; reintegroMaximo: string; extraordinarioMaximo: string; umbralDiferencia: string }

const cajaVacia: CajaEdicion = { codigo: '', nombre: '', tipo: 'VENTAS', estado: 'DISPONIBLE', motivo: '' }
const pestanas: Array<{ id: Pestana; etiqueta: string }> = [{ id: 'politica', etiqueta: 'Política operativa' }, { id: 'cajas', etiqueta: 'Cajas físicas' }]
function filtroLista(filtros: ColumnFiltersState, id: string): string[] | undefined { const valor = filtros.find((filtro) => filtro.id === id)?.value; return Array.isArray(valor) ? valor.filter((item): item is string => typeof item === 'string') : undefined }
function textoCentavos(valor: number | null): string { return valor === null ? '' : (valor / 100).toFixed(2) }
function valoresDePolitica(politica: PoliticaCaja | null): ValoresPolitica { return { horaInicio: politica?.horaInicioDia ?? '00:00', horaFin: politica?.horaFinDia ?? '23:59', fondoMaximo: textoCentavos(politica?.fondoMaximoCentavos ?? null), saldoMaximo: textoCentavos(politica?.saldoMaximoCentavos ?? null), reintegroMaximo: textoCentavos(politica?.reintegroMaximoCentavos ?? null), extraordinarioMaximo: textoCentavos(politica?.movimientoExtraordinarioMaximoCentavos ?? null), umbralDiferencia: textoCentavos(politica?.umbralDiferenciaCentavos ?? null) } }

export function ConfiguracionCajaView({ permisos, onNavegar, onCambiosPendientes }: Props) {
  const puedeVerCajas = permisos.includes('CAJA.CAJAS.VER')
  const puedeVerPoliticas = permisos.includes('CAJA.POLITICAS.VER')
  const puedeCrearCajas = permisos.includes('CAJA.CAJAS.CREAR')
  const puedeCajas = permisos.includes('CAJA.CAJAS.ACTUALIZAR')
  const puedePoliticas = permisos.includes('CAJA.POLITICAS.CONFIGURAR')
  const corporativo = permisos.includes('CAJA.CORPORATIVO.VER')
  const puedeAuditoriaCajas = permisos.includes('CAJA.CAJAS.VER_AUDITORIA')
  const puedeAuditoriaPoliticas = permisos.includes('CAJA.POLITICAS.VER_AUDITORIA')
  const [opciones, setOpciones] = useState<OpcionesFiltrosCaja | null>(null)
  const [politicas, setPoliticas] = useState<ResultadoPaginado<PoliticaCaja> | null>(null)
  const [cajas, setCajas] = useState<ResultadoPaginado<CajaConfiguracion> | null>(null)
  const pestanasVisibles = useMemo(
    () => pestanas.filter((item) => item.id === 'politica' ? puedeVerPoliticas : puedeVerCajas),
    [puedeVerCajas, puedeVerPoliticas],
  )
  const [pestana, setPestana] = useState<Pestana>(puedeVerPoliticas ? 'politica' : 'cajas')
  const [pestanaPendiente, setPestanaPendiente] = useState<Pestana | null>(null)
  const [vistaPolitica, setVistaPolitica] = useState<VistaPolitica>('listado')
  const [politica, setPolitica] = useState<PoliticaCaja | null>(null)
  const [politicaOriginal, setPoliticaOriginal] = useState('')
  const [confirmarCancelacion, setConfirmarCancelacion] = useState(false)
  const [sucursalPoliticaId, setSucursalPoliticaId] = useState('')
  const [horaInicio, setHoraInicio] = useState('00:00')
  const [horaFin, setHoraFin] = useState('23:59')
  const [fondoMaximo, setFondoMaximo] = useState('')
  const [saldoMaximo, setSaldoMaximo] = useState('')
  const [reintegroMaximo, setReintegroMaximo] = useState('')
  const [extraordinarioMaximo, setExtraordinarioMaximo] = useState('')
  const [umbralDiferencia, setUmbralDiferencia] = useState('')
  const [motivoPolitica, setMotivoPolitica] = useState('')
  const [paginaPolitica, setPaginaPolitica] = useState(1)
  const [tamanoPolitica, setTamanoPolitica] = useState(50)
  const [busquedaPoliticaEntrada, setBusquedaPoliticaEntrada] = useState('')
  const [busquedaPolitica, setBusquedaPolitica] = useState('')
  const [filtrosPolitica, setFiltrosPolitica] = useState<ColumnFiltersState>([])
  const [ordenPolitica, setOrdenPolitica] = useState<SortingState>([{ id: 'actualizacion', desc: true }])
  const [paginaCaja, setPaginaCaja] = useState(1)
  const [tamanoCaja, setTamanoCaja] = useState(50)
  const [busquedaCajaEntrada, setBusquedaCajaEntrada] = useState('')
  const [busquedaCaja, setBusquedaCaja] = useState('')
  const [filtrosCaja, setFiltrosCaja] = useState<ColumnFiltersState>([])
  const [ordenCaja, setOrdenCaja] = useState<SortingState>([{ id: 'codigo', desc: false }])
  const [cajaEdicion, setCajaEdicion] = useState<CajaEdicion | null>(null)
  const [auditoriaCaja, setAuditoriaCaja] = useState<CajaConfiguracion | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [errorAccion, setErrorAccion] = useState<string | null>(null)
  const [errorModal, setErrorModal] = useState<string | null>(null)
  const [exito, setExito] = useState<string | null>(null)
  const [procesando, setProcesando] = useState(false)
  const [revision, setRevision] = useState(0)
  const [cargaPolitica, setCargaPolitica] = useState('')
  const [cargaCaja, setCargaCaja] = useState('')

  const snapshot = JSON.stringify({ sucursalPoliticaId, horaInicio, horaFin, fondoMaximo, saldoMaximo, reintegroMaximo, extraordinarioMaximo, umbralDiferencia, motivoPolitica })
  const politicaModificada = vistaPolitica === 'edicion' && Boolean(politicaOriginal && politicaOriginal !== snapshot)
  useEffect(() => { onCambiosPendientes(politicaModificada); return () => onCambiosPendientes(false) }, [onCambiosPendientes, politicaModificada])
  useEffect(() => { const controlador = new AbortController(); void obtenerOpcionesCaja(controlador.signal).then((dato) => setOpciones(dato)).catch((actual: unknown) => { if (!controlador.signal.aborted) setError(actual instanceof ErrorApi ? actual.message : 'No fue posible cargar las opciones de configuración.') }); return () => controlador.abort() }, [revision])
  useEffect(() => { const t = window.setTimeout(() => { setBusquedaPolitica(busquedaPoliticaEntrada.trim().replace(/\s+/g, ' ')); setPaginaPolitica(1) }, 400); return () => window.clearTimeout(t) }, [busquedaPoliticaEntrada])
  useEffect(() => { const t = window.setTimeout(() => { setBusquedaCaja(busquedaCajaEntrada.trim().replace(/\s+/g, ' ')); setPaginaCaja(1) }, 400); return () => window.clearTimeout(t) }, [busquedaCajaEntrada])

  const parametrosPolitica = useMemo(() => ({ pagina: paginaPolitica, tamanoPagina: tamanoPolitica, busqueda: busquedaPolitica || undefined, sucursalIds: filtroLista(filtrosPolitica, 'sucursal'), orden: ordenPolitica[0]?.id ?? 'actualizacion', direccion: ordenPolitica[0]?.desc ? 'desc' as const : 'asc' as const }), [busquedaPolitica, filtrosPolitica, ordenPolitica, paginaPolitica, tamanoPolitica])
  const parametrosCaja = useMemo(() => ({ pagina: paginaCaja, tamanoPagina: tamanoCaja, busqueda: busquedaCaja || undefined, estados: filtroLista(filtrosCaja, 'estado'), tipos: filtroLista(filtrosCaja, 'tipo'), sucursalIds: filtroLista(filtrosCaja, 'sucursal'), orden: ordenCaja[0]?.id ?? 'codigo', direccion: ordenCaja[0]?.desc ? 'desc' as const : 'asc' as const }), [busquedaCaja, filtrosCaja, ordenCaja, paginaCaja, tamanoCaja])
  const clavePolitica = useMemo(() => JSON.stringify({ parametrosPolitica, revision }), [parametrosPolitica, revision])
  const claveCaja = useMemo(() => JSON.stringify({ parametrosCaja, revision }), [parametrosCaja, revision])
  const cargandoPoliticas = puedeVerPoliticas && cargaPolitica !== clavePolitica
  const cargandoCajas = puedeVerCajas && cargaCaja !== claveCaja
  useEffect(() => { if (!puedeVerPoliticas) return; const controlador = new AbortController(); void listarCaja<PoliticaCaja>('politicas', parametrosPolitica, controlador.signal).then((dato) => { if (dato.totalPaginas > 0 && paginaPolitica > dato.totalPaginas) setPaginaPolitica(dato.totalPaginas); else setPoliticas(dato); setError(null) }).catch((actual: unknown) => { if (!controlador.signal.aborted) setError(actual instanceof ErrorApi ? actual.message : 'No fue posible cargar las políticas operativas.') }).finally(() => { if (!controlador.signal.aborted) setCargaPolitica(clavePolitica) }); return () => controlador.abort() }, [clavePolitica, paginaPolitica, parametrosPolitica, puedeVerPoliticas])
  useEffect(() => { if (!puedeVerCajas) return; const controlador = new AbortController(); void listarCaja<CajaConfiguracion>('cajas', parametrosCaja, controlador.signal).then((dato) => { if (dato.totalPaginas > 0 && paginaCaja > dato.totalPaginas) setPaginaCaja(dato.totalPaginas); else setCajas(dato); setError(null) }).catch((actual: unknown) => { if (!controlador.signal.aborted) setError(actual instanceof ErrorApi ? actual.message : 'No fue posible cargar las cajas físicas.') }).finally(() => { if (!controlador.signal.aborted) setCargaCaja(claveCaja) }); return () => controlador.abort() }, [claveCaja, paginaCaja, parametrosCaja, puedeVerCajas])

  const opcionesSucursales = useMemo(() => opciones?.sucursales.map((item) => ({ valor: item.id, etiqueta: item.nombre, descripcion: item.codigo })) ?? [], [opciones])
  const cargarFormulario = useCallback((seleccion: PoliticaCaja | null) => {
    const valores = valoresDePolitica(seleccion); const sucursalId = seleccion?.sucursalId ?? ''
    setPolitica(seleccion); setSucursalPoliticaId(sucursalId); setHoraInicio(valores.horaInicio); setHoraFin(valores.horaFin); setFondoMaximo(valores.fondoMaximo); setSaldoMaximo(valores.saldoMaximo); setReintegroMaximo(valores.reintegroMaximo); setExtraordinarioMaximo(valores.extraordinarioMaximo); setUmbralDiferencia(valores.umbralDiferencia); setMotivoPolitica(''); setPoliticaOriginal(JSON.stringify({ sucursalPoliticaId: sucursalId, ...valores, motivoPolitica: '' })); setErrorAccion(null)
  }, [])
  const editarPolitica = useCallback((seleccion: PoliticaCaja | null) => { cargarFormulario(seleccion); setVistaPolitica('edicion') }, [cargarFormulario])
  const descartarPolitica = () => { setVistaPolitica('listado'); setPolitica(null); setPoliticaOriginal(''); setConfirmarCancelacion(false); if (pestanaPendiente) { setPestana(pestanaPendiente); setPestanaPendiente(null) } }
  const cambiarPestana = (destino: Pestana) => { if (destino === pestana) return; if (politicaModificada) setPestanaPendiente(destino); else setPestana(destino) }
  const tecladoPestanas = (evento: KeyboardEvent<HTMLButtonElement>, indice: number) => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(evento.key)) return; evento.preventDefault(); const siguiente = evento.key === 'Home' ? 0 : evento.key === 'End' ? pestanasVisibles.length - 1 : (indice + (evento.key === 'ArrowRight' ? 1 : -1) + pestanasVisibles.length) % pestanasVisibles.length; document.getElementById(`pestana-configuracion-${pestanasVisibles[siguiente].id}`)?.focus(); cambiarPestana(pestanasVisibles[siguiente].id) }

  const columnasPolitica = useMemo<ColumnaTabla<PoliticaCaja>[]>(() => [
    { id: 'sucursal', titulo: 'Sucursal', obtenerValor: (item) => item.sucursal?.nombre ?? item.sucursalId, filtro: opcionesSucursales.length ? { tipo: 'opciones', etiqueta: 'Seleccionar sucursales', multiple: true, opciones: opcionesSucursales } : undefined, celda: (item) => <div className={styles.identidad}><strong>{item.sucursal?.nombre ?? 'Sucursal activa'}</strong><small>{item.sucursal?.codigo ?? item.sucursalId}</small></div> },
    { id: 'horario', titulo: 'Horario operativo', obtenerValor: (item) => item.horaInicioDia, celda: (item) => <strong>{item.horaInicioDia} - {item.horaFinDia}</strong> },
    { id: 'fondo', titulo: 'Fondo máximo', obtenerValor: (item) => item.fondoMaximoCentavos ?? -1, celda: (item) => formatearCentavos(item.fondoMaximoCentavos) },
    { id: 'saldo', titulo: 'Saldo máximo', obtenerValor: (item) => item.saldoMaximoCentavos ?? -1, celda: (item) => formatearCentavos(item.saldoMaximoCentavos) },
    { id: 'umbral', titulo: 'Umbral de diferencia', obtenerValor: (item) => item.umbralDiferenciaCentavos ?? -1, celda: (item) => formatearCentavos(item.umbralDiferenciaCentavos) },
    { id: 'actualizacion', titulo: 'Última actualización', obtenerValor: (item) => item.actualizadoEn ?? item.creadoEn, ordenable: true, celda: (item) => <div className={styles.identidad}><strong>{formatearFechaHora(item.actualizadoEn ?? item.creadoEn)}</strong><small>Versión {item.version}</small></div> },
    { id: 'acciones', titulo: 'Acciones', tituloSoloLectores: true, obtenerValor: (item) => item.id, celda: (item) => <div className={styles.accionesFila}><button type="button" title="Ver política" onClick={() => { setPolitica(item); setVistaPolitica('detalle') }}><img src={iconoVer} alt="" /></button>{puedePoliticas && <button type="button" title="Editar política" onClick={() => editarPolitica(item)}><img src={iconoEditar} alt="" /></button>}</div> },
  ], [editarPolitica, opcionesSucursales, puedePoliticas])
  const columnasCaja = useMemo<ColumnaTabla<CajaConfiguracion>[]>(() => [
    { id: 'codigo', titulo: 'Código', obtenerValor: (item) => item.codigo, ordenable: true, celda: (item) => <strong>{item.codigo}</strong> },
    { id: 'nombre', titulo: 'Caja', obtenerValor: (item) => item.nombre, ordenable: true, celda: (item) => item.nombre },
    { id: 'tipo', titulo: 'Tipo', obtenerValor: (item) => item.tipo, filtro: { tipo: 'opciones', etiqueta: 'Seleccionar tipos', multiple: true, opciones: (opciones?.cajas.tipos ?? []).map((valor) => ({ valor, etiqueta: etiquetasTipoCaja[valor] })) }, celda: (item) => etiquetasTipoCaja[item.tipo] },
    ...(opcionesSucursales.length ? [{ id: 'sucursal', titulo: 'Sucursal', obtenerValor: (item: CajaConfiguracion) => item.sucursal?.nombre ?? item.sucursalId, filtro: { tipo: 'opciones' as const, etiqueta: 'Seleccionar sucursales', multiple: true, opciones: opcionesSucursales }, celda: (item: CajaConfiguracion) => item.sucursal?.nombre ?? item.sucursalId }] : []),
    { id: 'estado', titulo: 'Estado', obtenerValor: (item) => item.estado, ordenable: true, filtro: { tipo: 'opciones', etiqueta: 'Seleccionar estados', multiple: true, opciones: (opciones?.cajas.estados ?? []).map((valor) => ({ valor, etiqueta: etiquetasEstadoCaja[valor] })) }, celda: (item) => <span className={`${styles.estado} ${item.estado === 'DISPONIBLE' ? styles.estadoExito : item.estado === 'SUSPENDIDA' ? styles.estadoAdvertencia : styles.estadoPeligro}`}>{etiquetasEstadoCaja[item.estado]}</span> },
    { id: 'acciones', titulo: 'Acciones', tituloSoloLectores: true, obtenerValor: (item) => item.id, celda: (item) => <div className={styles.accionesFila}>{puedeAuditoriaCajas && <button type="button" title="Ver auditoría" onClick={() => setAuditoriaCaja(item)}><img src={iconoVer} alt="" /></button>}{puedeCajas && <button type="button" title="Editar caja" onClick={() => { setCajaEdicion({ id: item.id, codigo: item.codigo, nombre: item.nombre, tipo: item.tipo, estado: item.estado, motivo: '', version: item.version }); setErrorModal(null) }}><img src={iconoEditar} alt="" /></button>}</div> },
  ], [opciones, opcionesSucursales, puedeAuditoriaCajas, puedeCajas])

  const guardarPolitica = async () => {
    const convertir = (valor: string) => valor ? convertirQuetzalesACentavos(valor) : null
    if (corporativo && !sucursalPoliticaId) { setErrorAccion('Selecciona la sucursal a la que pertenece la política.'); return }
    if ([fondoMaximo, saldoMaximo, reintegroMaximo, extraordinarioMaximo, umbralDiferencia].some((valor) => valor && convertir(valor) === null)) { setErrorAccion('Revisa los montos configurados. Solo se permiten valores con hasta dos decimales.'); return }
    if (motivoPolitica.trim().length < 5) { setErrorAccion('El motivo debe contener al menos 5 caracteres.'); return }
    setProcesando(true)
    try { await configurarPoliticaCaja({ horaInicioDia: horaInicio, horaFinDia: horaFin, fondoMaximoCentavos: convertir(fondoMaximo), saldoMaximoCentavos: convertir(saldoMaximo), reintegroMaximoCentavos: convertir(reintegroMaximo), movimientoExtraordinarioMaximoCentavos: convertir(extraordinarioMaximo), umbralDiferenciaCentavos: convertir(umbralDiferencia), motivo: motivoPolitica.trim(), version: politica?.version }, corporativo ? sucursalPoliticaId : undefined); setPoliticaOriginal(''); setPolitica(null); setVistaPolitica('listado'); setExito('La política operativa quedó guardada.'); setRevision((valor) => valor + 1) }
    catch (actual: unknown) { setErrorAccion(actual instanceof ErrorApi ? actual.message : 'No fue posible guardar la política.') } finally { setProcesando(false) }
  }
  const guardarCaja = async () => { if (!cajaEdicion) return; if (cajaEdicion.codigo.trim().length < 2 || cajaEdicion.nombre.trim().length < 3) { setErrorModal('El código debe tener al menos 2 caracteres y el nombre al menos 3.'); return } if (cajaEdicion.id && cajaEdicion.motivo.trim().length < 5) { setErrorModal('El motivo debe contener al menos 5 caracteres.'); return } setProcesando(true); try { if (cajaEdicion.id) await actualizarCajaConfiguracion(cajaEdicion.id, { codigo: cajaEdicion.codigo.trim().toUpperCase(), nombre: cajaEdicion.nombre.trim(), tipo: cajaEdicion.tipo, estado: cajaEdicion.estado, motivo: cajaEdicion.motivo.trim(), version: cajaEdicion.version! }); else await crearCajaConfiguracion({ codigo: cajaEdicion.codigo.trim().toUpperCase(), nombre: cajaEdicion.nombre.trim(), tipo: cajaEdicion.tipo }); setCajaEdicion(null); setExito(cajaEdicion.id ? 'La caja quedó actualizada.' : 'La caja quedó registrada.'); setRevision((valor) => valor + 1) } catch (actual: unknown) { setErrorModal(actual instanceof ErrorApi ? actual.message : 'No fue posible guardar la caja.') } finally { setProcesando(false) } }
  const exportarCajas = async (formato: FormatoExportacion) => { const { pagina: _p, tamanoPagina: _t, ...filtros } = parametrosCaja; try { await exportarCaja('cajas', formato, filtros) } catch (actual: unknown) { setErrorAccion(actual instanceof ErrorApi ? actual.message : 'No fue posible exportar las cajas.') } }
  const auditoriaPolitica = useCallback((consulta: ConsultaAuditoria, signal?: AbortSignal) => politica ? listarAuditoriaCaja('POLITICA_CAJA', politica.id, consulta, signal) : Promise.reject(new Error('No hay política seleccionada.')), [politica])
  const cargarAuditoriaCaja = useCallback((consulta: ConsultaAuditoria, signal?: AbortSignal) => auditoriaCaja ? listarAuditoriaCaja('CAJA', auditoriaCaja.id, consulta, signal) : Promise.reject(new Error('No hay caja seleccionada.')), [auditoriaCaja])

  return <section className={styles.pagina} aria-labelledby="titulo-configuracion-caja"><header className={styles.cabeceraPagina}><CajaBreadcrumb seccion="Configuración" onNavegar={onNavegar} /><div><p className={styles.sobretitulo}>Parámetros operativos</p><h1 id="titulo-configuracion-caja">Configuración de caja</h1><p>Administra políticas operativas por sucursal y sus cajas físicas.</p></div></header>
    {error && <div className={styles.alertaError} role="alert"><p>{error}</p><button type="button" onClick={() => { setError(null); setRevision((valor) => valor + 1) }}>Reintentar</button></div>}
    <div className={styles.pestanasConfiguracion} role="tablist">{pestanasVisibles.map((item, indice) => <button key={item.id} id={`pestana-configuracion-${item.id}`} className={pestana === item.id ? styles.pestanaActiva : undefined} type="button" role="tab" aria-selected={pestana === item.id} onClick={() => cambiarPestana(item.id)} onKeyDown={(evento) => tecladoPestanas(evento, indice)}>{item.etiqueta}</button>)}</div>
    {puedeVerPoliticas && pestana === 'politica' && <div className={styles.panelPestana} role="tabpanel">
      {vistaPolitica === 'listado' && <article className={styles.panelTabla} aria-busy={cargandoPoliticas}><div className={styles.resumenTabla}><div><strong>Políticas operativas</strong><small>{corporativo ? 'Políticas configuradas por sucursal.' : 'Política vigente para la sucursal activa.'}</small></div><div className={`${styles.accionesResumen} ${styles.accionesResumenEnFila}`}>{puedePoliticas && (corporativo || !politicas?.total) && <button className={styles.botonNuevo} type="button" onClick={() => editarPolitica(null)}><IconoAccion nombre="agregar" />Nueva política</button>}<label className={styles.busquedaCompacta}><span className={styles.controlBusqueda}><img src={iconoBusqueda} alt="" /><input type="search" value={busquedaPoliticaEntrada} placeholder="Código o nombre de sucursal" aria-label="Buscar política por sucursal" onChange={(evento) => setBusquedaPoliticaEntrada(evento.target.value)} /></span></label></div></div>{politicas?.items.length ? <><TablaDatos descripcion="Políticas operativas por sucursal" datos={politicas.items} columnas={columnasPolitica} filtros={filtrosPolitica} ordenamiento={ordenPolitica} obtenerIdFila={(item) => item.id} onFiltrosChange={(valor) => { setFiltrosPolitica(valor); setPaginaPolitica(1) }} onOrdenamientoChange={(valor) => { setOrdenPolitica(valor.length ? valor : [{ id: 'actualizacion', desc: true }]); setPaginaPolitica(1) }} /><PaginacionTabla pagina={politicas.pagina} tamanoPagina={politicas.tamanoPagina} total={politicas.total} totalPaginas={politicas.totalPaginas} unidadSingular="política" unidadPlural="políticas" onPaginaChange={setPaginaPolitica} onTamanoPaginaChange={(valor) => { setTamanoPolitica(valor); setPaginaPolitica(1) }} /></> : !cargandoPoliticas ? <div className={styles.estadoVacio}><h2>{busquedaPolitica ? 'Sin coincidencias' : 'No hay una política configurada'}</h2><p>{busquedaPolitica ? 'Ajusta la búsqueda o los filtros.' : 'Registra la política operativa para definir horarios, límites y umbrales.'}</p>{puedePoliticas && <button type="button" onClick={() => editarPolitica(null)}><IconoAccion nombre="agregar" />Crear política</button>}</div> : null}</article>}
      {vistaPolitica === 'detalle' && politica && <><article className={styles.tarjetaDetalle}><div className={styles.tituloSeccion}><div><h2>Detalle de política operativa</h2><p>{politica.sucursal ? `${politica.sucursal.codigo} · ${politica.sucursal.nombre}` : 'Sucursal activa'}</p></div><span>Versión {politica.version}</span></div><dl><div><dt>Inicio del día</dt><dd>{politica.horaInicioDia}</dd></div><div><dt>Fin del día</dt><dd>{politica.horaFinDia}</dd></div><div><dt>Fondo máximo</dt><dd>{formatearCentavos(politica.fondoMaximoCentavos)}</dd></div><div><dt>Saldo máximo</dt><dd>{formatearCentavos(politica.saldoMaximoCentavos)}</dd></div><div><dt>Reintegro máximo</dt><dd>{formatearCentavos(politica.reintegroMaximoCentavos)}</dd></div><div><dt>Movimiento extraordinario</dt><dd>{formatearCentavos(politica.movimientoExtraordinarioMaximoCentavos)}</dd></div><div><dt>Umbral de diferencia</dt><dd>{formatearCentavos(politica.umbralDiferenciaCentavos)}</dd></div><div><dt>Última actualización</dt><dd>{formatearFechaHora(politica.actualizadoEn ?? politica.creadoEn)}</dd></div></dl><div className={styles.accionesFormulario}><button className={styles.botonNeutral} type="button" onClick={() => { setPolitica(null); setVistaPolitica('listado') }}><IconoAccion nombre="cancelar" />Volver al listado</button>{puedePoliticas && <button className={styles.botonPrincipal} type="button" onClick={() => editarPolitica(politica)}><IconoAccion nombre="editar" />Editar política</button>}</div></article>{puedeAuditoriaPoliticas && <PistaAuditoria claveEntidad={`politica-${politica.id}`} descripcion={`Historial de la política de ${politica.sucursal?.nombre ?? 'la sucursal activa'}.`} etiquetasOperacion={{ CREAR_POLITICA: 'Creación', ACTUALIZAR_POLITICA: 'Actualización' }} cargarEventos={auditoriaPolitica} revision={revision} />}</>}
      {vistaPolitica === 'edicion' && <article className={styles.tarjetaDetalle}><div className={styles.tituloSeccion}><div><h2>{politica ? 'Editar política operativa' : 'Nueva política operativa'}</h2><p>Los límites vacíos se consideran sin restricción configurada.</p></div>{politica && <span>Versión {politica.version}</span>}</div><div className={styles.grillaTres}>{corporativo && <div className={`${styles.campo} ${styles.campoDoble}`}><label htmlFor="sucursal-politica">Sucursal <span aria-hidden="true">*</span></label><select id="sucursal-politica" value={sucursalPoliticaId} disabled={Boolean(politica)} onChange={(evento) => setSucursalPoliticaId(evento.target.value)}><option value="">Selecciona una sucursal</option>{opciones?.sucursales.map((sucursal) => <option key={sucursal.id} value={sucursal.id}>{sucursal.codigo} · {sucursal.nombre}</option>)}</select></div>}<CampoPolitica id="hora-inicio-politica" etiqueta="Inicio del día" tipo="time" valor={horaInicio} onChange={setHoraInicio} /><CampoPolitica id="hora-fin-politica" etiqueta="Fin del día" tipo="time" valor={horaFin} onChange={setHoraFin} /><CampoPolitica id="fondo-maximo-politica" etiqueta="Fondo máximo (Q)" valor={fondoMaximo} onChange={setFondoMaximo} /><CampoPolitica id="saldo-maximo-politica" etiqueta="Saldo máximo (Q)" valor={saldoMaximo} onChange={setSaldoMaximo} /><CampoPolitica id="reintegro-maximo-politica" etiqueta="Reintegro máximo (Q)" valor={reintegroMaximo} onChange={setReintegroMaximo} /><CampoPolitica id="extraordinario-maximo-politica" etiqueta="Movimiento extraordinario máximo (Q)" valor={extraordinarioMaximo} onChange={setExtraordinarioMaximo} /><CampoPolitica id="umbral-politica" etiqueta="Umbral de diferencia (Q)" valor={umbralDiferencia} onChange={setUmbralDiferencia} /><div className={`${styles.campo} ${styles.campoDoble}`}><label htmlFor="motivo-politica">Motivo <span aria-hidden="true">*</span></label><textarea id="motivo-politica" rows={3} maxLength={500} value={motivoPolitica} onChange={(evento) => setMotivoPolitica(evento.target.value)} /></div></div><div className={styles.accionesFormulario}><p>La sucursal y el usuario quedan registrados por el servidor.</p><div><button className={styles.botonNeutral} type="button" disabled={procesando} onClick={() => politicaModificada ? setConfirmarCancelacion(true) : descartarPolitica()}><IconoAccion nombre="cancelar" />Cancelar</button><button className={styles.botonPrincipal} type="button" disabled={procesando} onClick={() => void guardarPolitica()}><IconoAccion nombre="guardar" />{procesando ? 'Guardando…' : 'Guardar política'}</button></div></div></article>}
    </div>}
    {puedeVerCajas && <article className={styles.panelTabla} role="tabpanel" hidden={pestana !== 'cajas'} aria-busy={cargandoCajas}><div className={styles.resumenTabla}><div><strong>Cajas físicas</strong><small>{corporativo ? 'Cajas de las sucursales autorizadas.' : 'Cajas de la sucursal activa.'}</small></div><div className={`${styles.accionesResumen} ${styles.accionesResumenEnFila}`}>{puedeCrearCajas && <button className={styles.botonNuevo} type="button" onClick={() => { setCajaEdicion({ ...cajaVacia }); setErrorModal(null) }}><IconoAccion nombre="agregar" />Nueva caja</button>}{permisos.includes('CAJA.CAJAS.EXPORTAR') && <BotonExportar deshabilitado={cargandoCajas} onExportar={exportarCajas} />}<label className={styles.busquedaCompacta}><span className={styles.controlBusqueda}><img src={iconoBusqueda} alt="" /><input type="search" value={busquedaCajaEntrada} placeholder="Código o nombre" aria-label="Buscar caja" onChange={(evento) => setBusquedaCajaEntrada(evento.target.value)} /></span></label></div></div>{cajas?.items.length ? <><TablaDatos descripcion="Cajas físicas" datos={cajas.items} columnas={columnasCaja} filtros={filtrosCaja} ordenamiento={ordenCaja} obtenerIdFila={(item) => item.id} onFiltrosChange={(valor) => { setFiltrosCaja(valor); setPaginaCaja(1) }} onOrdenamientoChange={(valor) => { setOrdenCaja(valor.length ? valor : [{ id: 'codigo', desc: false }]); setPaginaCaja(1) }} /><PaginacionTabla pagina={cajas.pagina} tamanoPagina={cajas.tamanoPagina} total={cajas.total} totalPaginas={cajas.totalPaginas} unidadSingular="caja" unidadPlural="cajas" onPaginaChange={setPaginaCaja} onTamanoPaginaChange={(valor) => { setTamanoCaja(valor); setPaginaCaja(1) }} /></> : !cargandoCajas ? <div className={styles.estadoVacio}><h2>No hay cajas registradas</h2><p>Registra la primera caja física para habilitar aperturas de turno.</p></div> : null}</article>}
    {auditoriaCaja && puedeAuditoriaCajas && <PistaAuditoria claveEntidad={`caja-${auditoriaCaja.id}`} descripcion={`Cambios de configuración de ${auditoriaCaja.nombre}.`} etiquetasOperacion={{ CREAR: 'Creación', ACTUALIZAR: 'Actualización' }} cargarEventos={cargarAuditoriaCaja} revision={revision} />}
    <ModalEstado abierto={Boolean(cajaEdicion)} tipo="informacion" titulo={cajaEdicion?.id ? 'Editar caja' : 'Registrar caja'} mensaje={cajaEdicion && <div className={styles.contenidoModal}><label htmlFor="codigo-caja">Código *</label><input id="codigo-caja" maxLength={30} value={cajaEdicion.codigo} onChange={(evento) => { setCajaEdicion({ ...cajaEdicion, codigo: evento.target.value }); setErrorModal(null) }} /><label htmlFor="nombre-caja">Nombre *</label><input id="nombre-caja" maxLength={120} value={cajaEdicion.nombre} onChange={(evento) => { setCajaEdicion({ ...cajaEdicion, nombre: evento.target.value }); setErrorModal(null) }} /><label htmlFor="tipo-caja">Tipo *</label><select id="tipo-caja" value={cajaEdicion.tipo} onChange={(evento) => setCajaEdicion({ ...cajaEdicion, tipo: evento.target.value as TipoCaja })}>{Object.entries(etiquetasTipoCaja).map(([valor, etiqueta]) => <option key={valor} value={valor}>{etiqueta}</option>)}</select>{cajaEdicion.id && <><label htmlFor="estado-caja">Estado *</label><select id="estado-caja" value={cajaEdicion.estado} onChange={(evento) => setCajaEdicion({ ...cajaEdicion, estado: evento.target.value as EstadoCaja })}>{Object.entries(etiquetasEstadoCaja).map(([valor, etiqueta]) => <option key={valor} value={valor}>{etiqueta}</option>)}</select><label htmlFor="motivo-caja">Motivo *</label><textarea id="motivo-caja" rows={3} value={cajaEdicion.motivo} onChange={(evento) => setCajaEdicion({ ...cajaEdicion, motivo: evento.target.value })} /></>}{errorModal && <small role="alert">{errorModal}</small>}</div>} textoAccionPrincipal={cajaEdicion?.id ? 'Guardar cambios' : 'Registrar caja'} onAccionPrincipal={() => void guardarCaja()} textoAccionSecundaria="Cancelar" onAccionSecundaria={() => setCajaEdicion(null)} onCerrar={() => setCajaEdicion(null)} cargando={procesando} />
    <ModalEstado abierto={Boolean(pestanaPendiente || confirmarCancelacion)} tipo="advertencia" titulo="Descartar cambios sin guardar" mensaje="Hay cambios en la política operativa que todavía no se han guardado." textoAccionPrincipal="Descartar cambios" varianteAccionPrincipal="peligro" onAccionPrincipal={descartarPolitica} textoAccionSecundaria="Seguir editando" onAccionSecundaria={() => { setPestanaPendiente(null); setConfirmarCancelacion(false) }} onCerrar={() => { setPestanaPendiente(null); setConfirmarCancelacion(false) }} />
    <ModalEstado abierto={Boolean(exito)} tipo="exito" titulo="Configuración guardada" mensaje={exito ?? ''} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => setExito(null)} onCerrar={() => setExito(null)} /><ModalEstado abierto={Boolean(errorAccion)} tipo="error" titulo="No se pudo completar la acción" mensaje={errorAccion ?? ''} textoAccionPrincipal="Entendido" onAccionPrincipal={() => setErrorAccion(null)} onCerrar={() => setErrorAccion(null)} />
  </section>
}

function CampoPolitica({ id, etiqueta, valor, tipo = 'number', onChange }: { id: string; etiqueta: string; valor: string; tipo?: 'number' | 'time'; onChange: (valor: string) => void }) { return <div className={styles.campo}><label htmlFor={id}>{etiqueta}</label><input id={id} type={tipo} min={tipo === 'number' ? '0' : undefined} step={tipo === 'number' ? '0.01' : undefined} value={valor} onChange={(evento) => onChange(evento.target.value)} /></div> }
