import { useCallback, useEffect, useState } from 'react'
import { PistaAuditoria, type ConsultaAuditoria } from '../../../shared/auditoria'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { confirmarDepositoCaja, listarAuditoriaCaja, listarCaja, obtenerDepositoCaja, obtenerTransferenciaCaja, recibirTransferenciaCaja, registrarDepositoCaja } from '../caja-api'
import { convertirQuetzalesACentavos, etiquetasCustodia, etiquetasEstadoDeposito, etiquetasEstadoTransferencia, formatearCentavos, formatearFecha, formatearFechaHora } from '../caja-formatos'
import type { DepositoEfectivo, TransferenciaEfectivo, TurnoCaja } from '../caja.types'
import { CajaBreadcrumb } from './caja-breadcrumb'
import styles from './caja.module.css'
import { EvidenciasCaja } from './evidencias-caja'

type Props = { permisos: readonly string[]; onNavegar: (ruta: string) => void }
function Motivo({ valor, error, onChange }: { valor: string; error: string | null; onChange: (valor: string) => void }) { return <div className={styles.contenidoModal}><p>La acción quedará registrada en la pista de auditoría.</p><label htmlFor="motivo-custodia">Motivo <span aria-hidden="true">*</span></label><textarea id="motivo-custodia" rows={4} maxLength={500} value={valor} aria-invalid={Boolean(error)} onChange={(e) => onChange(e.target.value)} />{error && <small>{error}</small>}</div> }

export function TransferenciaDetalleView({ transferenciaId, permisos, onNavegar }: Props & { transferenciaId: string }) {
  const [transferencia, setTransferencia] = useState<TransferenciaEfectivo | null>(null)
  const [turnos, setTurnos] = useState<TurnoCaja[]>([])
  const [solicitudFinalizada, setSolicitudFinalizada] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [mostrarRecepcion, setMostrarRecepcion] = useState(false)
  const [turnoDestinoId, setTurnoDestinoId] = useState('')
  const [motivo, setMotivo] = useState('')
  const [errorMotivo, setErrorMotivo] = useState<string | null>(null)
  const [procesando, setProcesando] = useState(false)
  const [mensajeExito, setMensajeExito] = useState<string | null>(null)
  const [errorAccion, setErrorAccion] = useState<string | null>(null)
  const [revision, setRevision] = useState(0)
  const claveSolicitud = `${transferenciaId}:${revision}`
  const cargando = solicitudFinalizada !== claveSolicitud
  useEffect(() => { const controlador = new AbortController(); void Promise.all([obtenerTransferenciaCaja(transferenciaId, controlador.signal), listarCaja<TurnoCaja>('turnos', { pagina: 1, tamanoPagina: 200, estados: ['ABIERTO', 'REABIERTO'], orden: 'fecha', direccion: 'desc' }, controlador.signal)]).then(([dato, turnosRespuesta]) => { setTransferencia(dato); setTurnos(turnosRespuesta.items); setError(null) }).catch((errorActual: unknown) => { if (!controlador.signal.aborted) setError(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible cargar la transferencia.') }).finally(() => { if (!controlador.signal.aborted) setSolicitudFinalizada(claveSolicitud) }); return () => controlador.abort() }, [claveSolicitud, transferenciaId])
  const turnosDestino = transferencia?.cajaDestinoId ? turnos.filter((turno) => turno.cajaId === transferencia.cajaDestinoId) : turnos
  const cargarAuditoria = useCallback((consulta: ConsultaAuditoria, signal?: AbortSignal) => listarAuditoriaCaja('TRANSFERENCIA_EFECTIVO', transferenciaId, consulta, signal), [transferenciaId])
  const recibir = async () => {
    if (!transferencia) return
    if (transferencia.cajaDestinoId && !turnoDestinoId) { setErrorMotivo('Selecciona el turno abierto de la caja destino.'); return }
    if (motivo.trim().length < 5) { setErrorMotivo('El motivo debe contener al menos 5 caracteres.'); return }
    setProcesando(true); setErrorAccion(null)
    try { const dato = await recibirTransferenciaCaja(transferencia.id, { turnoDestinoId: turnoDestinoId || null, version: transferencia.version, motivo: motivo.trim() }); setTransferencia(dato); setMostrarRecepcion(false); setMotivo(''); setTurnoDestinoId(''); setMensajeExito(`La recepción de ${dato.numero} quedó registrada.`); setRevision((v) => v + 1) }
    catch (errorActual: unknown) { setMostrarRecepcion(false); setErrorAccion(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible recibir la transferencia.') }
    finally { setProcesando(false) }
  }
  if (cargando && !transferencia) return <section className={styles.pagina}><p role="status">Cargando transferencia…</p></section>
  if (error || !transferencia) return <section className={styles.pagina}><CajaBreadcrumb seccion="Custodia y transferencias" actual="Detalle" onNavegar={onNavegar} /><div className={styles.alertaError} role="alert"><p>{error ?? 'La transferencia no está disponible.'}</p><button type="button" onClick={() => setRevision((v) => v + 1)}>Reintentar</button></div></section>
  return <section className={styles.pagina} aria-labelledby="titulo-detalle-transferencia"><CajaBreadcrumb seccion="Custodia y transferencias" actual={transferencia.numero} onNavegar={onNavegar} /><header className={styles.cabeceraDetalle}><div><p className={styles.sobretitulo}>Cadena de custodia</p><h1 id="titulo-detalle-transferencia">{transferencia.numero}</h1><p>{etiquetasCustodia[transferencia.custodiaOrigen]} → {etiquetasCustodia[transferencia.custodiaDestino]}</p><span className={`${styles.estado} ${transferencia.estado === 'RECIBIDA' ? styles.estadoExito : transferencia.estado === 'RECHAZADA' || transferencia.estado === 'CANCELADA' ? styles.estadoPeligro : styles.estadoAdvertencia}`}>{etiquetasEstadoTransferencia[transferencia.estado]}</span></div><div className={styles.accionesCabecera}>{permisos.includes('CAJA.INCIDENCIAS.CREAR') && <button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`/caja/incidencias/nueva?entidadTipo=TRANSFERENCIA_EFECTIVO&entidadId=${transferencia.id}`)}><IconoAccion nombre="agregar" />Reportar incidencia</button>}{permisos.includes('CAJA.TRANSFERENCIAS.RECIBIR') && transferencia.estado === 'ENTREGADA' && <button className={styles.botonPrincipal} type="button" onClick={() => setMostrarRecepcion(true)}><IconoAccion nombre="guardar" />Registrar recepción</button>}</div></header>
    <div className={styles.grillaDetalle}><article className={styles.tarjetaDetalle}><h2>Origen y destino</h2><dl><div><dt>Turno origen</dt><dd>{transferencia.turnoOrigenNumero ?? transferencia.turnoOrigenId ?? 'Sin turno'}</dd></div><div><dt>Caja destino</dt><dd>{transferencia.cajaDestino ? `${transferencia.cajaDestino.codigo} · ${transferencia.cajaDestino.nombre}` : 'No aplica'}</dd></div><div><dt>Custodia origen</dt><dd>{etiquetasCustodia[transferencia.custodiaOrigen]}</dd></div><div><dt>Custodia destino</dt><dd>{etiquetasCustodia[transferencia.custodiaDestino]}</dd></div><div><dt>Monto</dt><dd><strong>{formatearCentavos(transferencia.montoCentavos)}</strong></dd></div><div className={styles.datoCompleto}><dt>Motivo</dt><dd>{transferencia.motivo}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Seguridad y transporte</h2><dl><div><dt>Bolsa</dt><dd>{transferencia.bolsa ?? 'No registrada'}</dd></div><div><dt>Sello</dt><dd>{transferencia.sello ?? 'No registrado'}</dd></div><div><dt>Transporte</dt><dd>{transferencia.transporte ?? 'No registrado'}</dd></div><div><dt>Receptor</dt><dd>{transferencia.receptorNombre ?? 'Pendiente'}</dd></div><div><dt>Entregado</dt><dd>{formatearFechaHora(transferencia.entregadoEn)}</dd></div><div><dt>Recibido</dt><dd>{formatearFechaHora(transferencia.recibidoEn)}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Movimientos relacionados</h2><dl><div><dt>Movimiento de salida</dt><dd>{transferencia.movimientoSalidaId ? <button className={styles.enlaceTexto} type="button" onClick={() => onNavegar(`/caja/movimientos/${transferencia.movimientoSalidaId}`)}>Ver movimiento</button> : 'Pendiente'}</dd></div><div><dt>Movimiento de entrada</dt><dd>{transferencia.movimientoEntradaId ? <button className={styles.enlaceTexto} type="button" onClick={() => onNavegar(`/caja/movimientos/${transferencia.movimientoEntradaId}`)}>Ver movimiento</button> : 'No aplica o pendiente'}</dd></div><div><dt>Versión</dt><dd>{transferencia.version}</dd></div></dl></article></div>
    <EvidenciasCaja entidadTipo="TRANSFERENCIA_EFECTIVO" entidadId={transferencia.id} permisos={permisos} revision={revision} onCambio={() => setRevision((v) => v + 1)} />{permisos.includes('CAJA.TRANSFERENCIAS.VER_AUDITORIA') && <PistaAuditoria claveEntidad={`transferencia-${transferencia.id}`} descripcion="Entrega, recepción, responsables y cambios de custodia de la transferencia." etiquetasOperacion={{ ENTREGAR_TRANSFERENCIA: 'Entrega', RECIBIR_TRANSFERENCIA: 'Recepción', ADJUNTAR_EVIDENCIA: 'Evidencia adjunta' }} cargarEventos={cargarAuditoria} revision={revision} />}
    <ModalEstado abierto={mostrarRecepcion} tipo="informacion" titulo="Registrar recepción" mensaje={<div className={styles.contenidoModal}>{transferencia.cajaDestinoId && <><label htmlFor="turno-destino-transferencia">Turno receptor <span aria-hidden="true">*</span></label><select id="turno-destino-transferencia" value={turnoDestinoId} onChange={(e) => { setTurnoDestinoId(e.target.value); setErrorMotivo(null) }}><option value="">Selecciona el turno de la caja destino</option>{turnosDestino.map((turno) => <option key={turno.id} value={turno.id}>{turno.numero} · {turno.responsableNombre}</option>)}</select></>}<Motivo valor={motivo} error={errorMotivo} onChange={(v) => { setMotivo(v); setErrorMotivo(null) }} /></div>} textoAccionPrincipal="Confirmar recepción" onAccionPrincipal={() => void recibir()} textoAccionSecundaria="Cancelar" onAccionSecundaria={() => setMostrarRecepcion(false)} onCerrar={() => setMostrarRecepcion(false)} cargando={procesando} />
    <ModalEstado abierto={Boolean(mensajeExito)} tipo="exito" titulo="Recepción registrada" mensaje={mensajeExito ?? ''} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => setMensajeExito(null)} onCerrar={() => setMensajeExito(null)} /><ModalEstado abierto={Boolean(errorAccion)} tipo="error" titulo="No se pudo completar la acción" mensaje={errorAccion ?? ''} textoAccionPrincipal="Entendido" onAccionPrincipal={() => setErrorAccion(null)} onCerrar={() => setErrorAccion(null)} />
  </section>
}

export function DepositoDetalleView({ depositoId, permisos, onNavegar }: Props & { depositoId: string }) {
  const [deposito, setDeposito] = useState<DepositoEfectivo | null>(null)
  const [solicitudFinalizada, setSolicitudFinalizada] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [accion, setAccion] = useState<'registrar' | 'confirmar' | null>(null)
  const [montoDepositado, setMontoDepositado] = useState('')
  const [referencia, setReferencia] = useState('')
  const [observacion, setObservacion] = useState('')
  const [motivo, setMotivo] = useState('')
  const [errorAccion, setErrorAccion] = useState<string | null>(null)
  const [errorModal, setErrorModal] = useState<string | null>(null)
  const [procesando, setProcesando] = useState(false)
  const [mensajeExito, setMensajeExito] = useState<string | null>(null)
  const [revision, setRevision] = useState(0)
  const claveSolicitud = `${depositoId}:${revision}`
  const cargando = solicitudFinalizada !== claveSolicitud
  useEffect(() => { const controlador = new AbortController(); void obtenerDepositoCaja(depositoId, controlador.signal).then((dato) => { setDeposito(dato); setError(null) }).catch((errorActual: unknown) => { if (!controlador.signal.aborted) setError(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible cargar el depósito.') }).finally(() => { if (!controlador.signal.aborted) setSolicitudFinalizada(claveSolicitud) }); return () => controlador.abort() }, [claveSolicitud, depositoId])
  const cargarAuditoria = useCallback((consulta: ConsultaAuditoria, signal?: AbortSignal) => listarAuditoriaCaja('DEPOSITO_EFECTIVO', depositoId, consulta, signal), [depositoId])
  const diferenciaPrevia = deposito && montoDepositado ? (convertirQuetzalesACentavos(montoDepositado) ?? deposito.montoPreparadoCentavos) - deposito.montoPreparadoCentavos : null
  const ejecutar = async () => {
    if (!deposito || !accion) return
    setErrorModal(null)
    if (accion === 'registrar') {
      const centavos = convertirQuetzalesACentavos(montoDepositado)
      if (!centavos || centavos <= 0) { setErrorModal('Ingresa el monto efectivamente depositado.'); return }
      if (referencia.trim().length < 3) { setErrorModal('La referencia bancaria debe contener al menos 3 caracteres.'); return }
      if (centavos !== deposito.montoPreparadoCentavos && observacion.trim().length < 5) { setErrorModal('Explica la diferencia con al menos 5 caracteres.'); return }
      setProcesando(true)
      try { const dato = await registrarDepositoCaja(deposito.id, { version: deposito.version, montoDepositadoCentavos: centavos, referenciaBancaria: referencia.trim(), observacionDiferencia: observacion.trim() || null }); setDeposito(dato); setAccion(null); setMensajeExito(`El registro bancario de ${dato.numero} quedó guardado.`); setRevision((v) => v + 1) }
      catch (errorActual: unknown) { setAccion(null); setErrorAccion(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible registrar el depósito.') }
      finally { setProcesando(false) }
      return
    }
    if (motivo.trim().length < 5) { setErrorModal('El motivo debe contener al menos 5 caracteres.'); return }
    setProcesando(true)
    try { const dato = await confirmarDepositoCaja(deposito.id, { version: deposito.version, motivo: motivo.trim() }); setDeposito(dato); setAccion(null); setMensajeExito(`El depósito ${dato.numero} quedó confirmado.`); setRevision((v) => v + 1) }
    catch (errorActual: unknown) { setAccion(null); setErrorAccion(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible confirmar el depósito.') }
    finally { setProcesando(false) }
  }
  if (cargando && !deposito) return <section className={styles.pagina}><p role="status">Cargando depósito…</p></section>
  if (error || !deposito) return <section className={styles.pagina}><CajaBreadcrumb seccion="Depósitos bancarios" actual="Detalle" onNavegar={onNavegar} /><div className={styles.alertaError} role="alert"><p>{error ?? 'El depósito no está disponible.'}</p><button type="button" onClick={() => setRevision((v) => v + 1)}>Reintentar</button></div></section>
  return <section className={styles.pagina} aria-labelledby="titulo-detalle-deposito"><CajaBreadcrumb seccion="Depósitos bancarios" actual={deposito.numero} onNavegar={onNavegar} /><header className={styles.cabeceraDetalle}><div><p className={styles.sobretitulo}>Depósito bancario</p><h1 id="titulo-detalle-deposito">{deposito.numero}</h1><p>{deposito.cuenta ? `${deposito.cuenta.banco} · ${deposito.cuenta.alias} · ${deposito.cuenta.cuentaEnmascarada}` : 'Cuenta bancaria'}</p><span className={`${styles.estado} ${deposito.estado === 'CONFIRMADO' ? styles.estadoExito : deposito.estado === 'DIFERENCIA' || deposito.estado === 'CANCELADO' ? styles.estadoPeligro : styles.estadoAdvertencia}`}>{etiquetasEstadoDeposito[deposito.estado]}</span></div><div className={styles.accionesCabecera}>{permisos.includes('CAJA.INCIDENCIAS.CREAR') && <button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`/caja/incidencias/nueva?entidadTipo=DEPOSITO_EFECTIVO&entidadId=${deposito.id}`)}><IconoAccion nombre="agregar" />Reportar incidencia</button>}{permisos.includes('CAJA.DEPOSITOS.REGISTRAR') && ['PREPARADO', 'EN_CUSTODIA'].includes(deposito.estado) && <button className={styles.botonPrincipal} type="button" onClick={() => { setMontoDepositado((deposito.montoPreparadoCentavos / 100).toFixed(2)); setAccion('registrar') }}><IconoAccion nombre="guardar" />Registrar depósito</button>}{permisos.includes('CAJA.DEPOSITOS.CONFIRMAR') && ['REGISTRADO', 'DIFERENCIA'].includes(deposito.estado) && <button className={styles.botonPrincipal} type="button" onClick={() => setAccion('confirmar')}><IconoAccion nombre="guardar" />Confirmar depósito</button>}</div></header>
    <div className={styles.grillaDetalle}><article className={styles.tarjetaDetalle}><h2>Importes</h2><dl><div><dt>Preparado</dt><dd>{formatearCentavos(deposito.montoPreparadoCentavos)}</dd></div><div><dt>Depositado</dt><dd>{formatearCentavos(deposito.montoDepositadoCentavos)}</dd></div><div><dt>Diferencia</dt><dd><strong>{formatearCentavos(deposito.diferenciaCentavos)}</strong></dd></div><div><dt>Referencia bancaria</dt><dd>{deposito.referenciaBancaria ?? 'Pendiente'}</dd></div><div className={styles.datoCompleto}><dt>Observación de diferencia</dt><dd>{deposito.observacionDiferencia ?? 'No aplica'}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Custodia</h2><dl><div><dt>Bolsa</dt><dd>{deposito.bolsa}</dd></div><div><dt>Sello</dt><dd>{deposito.sello}</dd></div><div><dt>Transporte</dt><dd>{deposito.transporte ?? 'No registrado'}</dd></div><div><dt>Transferencia</dt><dd>{deposito.transferenciaNumero ?? 'Sin transferencia vinculada'}</dd></div><div><dt>Fecha de negocio</dt><dd>{formatearFecha(deposito.fechaNegocio)}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Fechas y control</h2><dl><div><dt>Preparado</dt><dd>{formatearFechaHora(deposito.preparadoEn)}</dd></div><div><dt>Depositado</dt><dd>{formatearFechaHora(deposito.depositadoEn)}</dd></div><div><dt>Confirmado</dt><dd>{formatearFechaHora(deposito.confirmadoEn)}</dd></div><div><dt>Versión</dt><dd>{deposito.version}</dd></div></dl></article></div>
    <EvidenciasCaja entidadTipo="DEPOSITO_EFECTIVO" entidadId={deposito.id} permisos={permisos} revision={revision} onCambio={() => setRevision((v) => v + 1)} />{permisos.includes('CAJA.DEPOSITOS.VER_AUDITORIA') && <PistaAuditoria claveEntidad={`deposito-${deposito.id}`} descripcion="Preparación, registro bancario, confirmación y diferencias del depósito." etiquetasOperacion={{ PREPARAR_DEPOSITO: 'Preparación', REGISTRAR_DEPOSITO: 'Registro bancario', CONFIRMAR_DEPOSITO: 'Confirmación', ADJUNTAR_EVIDENCIA: 'Evidencia adjunta' }} cargarEventos={cargarAuditoria} revision={revision} />}
    <ModalEstado abierto={accion === 'registrar'} tipo="informacion" titulo="Registrar depósito bancario" mensaje={<div className={styles.contenidoModal}><label htmlFor="monto-depositado">Monto depositado (Q) <span aria-hidden="true">*</span></label><input id="monto-depositado" type="number" min="0.01" step="0.01" value={montoDepositado} onChange={(e) => { setMontoDepositado(e.target.value); setErrorModal(null) }} /><label htmlFor="referencia-bancaria">Referencia bancaria <span aria-hidden="true">*</span></label><input id="referencia-bancaria" maxLength={150} value={referencia} onChange={(e) => { setReferencia(e.target.value); setErrorModal(null) }} /><label htmlFor="observacion-deposito">Observación {diferenciaPrevia !== null && diferenciaPrevia !== 0 && <span aria-hidden="true">*</span>}</label><textarea id="observacion-deposito" rows={3} maxLength={1000} value={observacion} onChange={(e) => { setObservacion(e.target.value); setErrorModal(null) }} />{diferenciaPrevia !== null && <p>Diferencia calculada: <strong>{formatearCentavos(diferenciaPrevia)}</strong></p>}{errorModal && <small>{errorModal}</small>}</div>} textoAccionPrincipal="Registrar depósito" onAccionPrincipal={() => void ejecutar()} textoAccionSecundaria="Cancelar" onAccionSecundaria={() => setAccion(null)} onCerrar={() => setAccion(null)} cargando={procesando} />
    <ModalEstado abierto={accion === 'confirmar'} tipo="informacion" titulo="Confirmar depósito" mensaje={<Motivo valor={motivo} error={errorModal} onChange={(v) => { setMotivo(v); setErrorModal(null) }} />} textoAccionPrincipal="Confirmar depósito" onAccionPrincipal={() => void ejecutar()} textoAccionSecundaria="Cancelar" onAccionSecundaria={() => setAccion(null)} onCerrar={() => setAccion(null)} cargando={procesando} /><ModalEstado abierto={Boolean(mensajeExito)} tipo="exito" titulo="Depósito actualizado" mensaje={mensajeExito ?? ''} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => setMensajeExito(null)} onCerrar={() => setMensajeExito(null)} /><ModalEstado abierto={Boolean(errorAccion)} tipo="error" titulo="No se pudo completar la acción" mensaje={errorAccion ?? ''} textoAccionPrincipal="Entendido" onAccionPrincipal={() => setErrorAccion(null)} onCerrar={() => setErrorAccion(null)} />
  </section>
}
