import { useCallback, useEffect, useState } from 'react'
import { PistaAuditoria, type ConsultaAuditoria } from '../../../shared/auditoria'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { aprobarConsolidacionCaja, aprobarRendicionCaja, confirmarConciliacionCaja, listarAuditoriaCaja, obtenerConciliacionCaja, obtenerConsolidacionCaja, obtenerRendicionCaja, reabrirConciliacionCaja, reabrirConsolidacionCaja } from '../caja-api'
import { etiquetasEstadoConciliacion, etiquetasEstadoConsolidacion, etiquetasEstadoRendicion, etiquetasTipoConciliacion, formatearCentavos, formatearFecha, formatearFechaHora } from '../caja-formatos'
import type { ConciliacionCaja, ConsolidacionDiariaCaja, RendicionRepartidor } from '../caja.types'
import { CajaBreadcrumb } from './caja-breadcrumb'
import { EvidenciasCaja } from './evidencias-caja'
import styles from './caja.module.css'

type Props = { permisos: readonly string[]; onNavegar: (ruta: string) => void }
type AccionConciliacion = 'confirmar' | 'reabrir' | null
type AccionConsolidacion = 'aprobar' | 'reabrir' | null

function claseEstado(estado: string): string { if (['APROBADA', 'CONCILIADA'].includes(estado)) return styles.estadoExito; if (['INVESTIGACION', 'DIFERENCIA'].includes(estado)) return styles.estadoPeligro; if (['PENDIENTE_APROBACION', 'PENDIENTE', 'PARCIAL'].includes(estado)) return styles.estadoAdvertencia; return styles.estadoNeutral }
function CampoMotivo({ id, valor, error, onChange }: { id: string; valor: string; error: string | null; onChange: (valor: string) => void }) { return <div className={styles.contenidoModal}><p>La acción quedará registrada en la pista de auditoría.</p><label htmlFor={id}>Motivo <span aria-hidden="true">*</span></label><textarea id={id} rows={4} maxLength={500} value={valor} aria-invalid={Boolean(error)} onChange={(evento) => onChange(evento.target.value)} />{error && <small role="alert">{error}</small>}</div> }

export function RendicionDetalleView({ rendicionId, permisos, onNavegar }: Props & { rendicionId: string }) {
  const [rendicion, setRendicion] = useState<RendicionRepartidor | null>(null)
  const [solicitudFinalizada, setSolicitudFinalizada] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [mostrarAprobacion, setMostrarAprobacion] = useState(false)
  const [motivo, setMotivo] = useState('')
  const [errorMotivo, setErrorMotivo] = useState<string | null>(null)
  const [procesando, setProcesando] = useState(false)
  const [mensajeExito, setMensajeExito] = useState<string | null>(null)
  const [errorAccion, setErrorAccion] = useState<string | null>(null)
  const [revision, setRevision] = useState(0)
  const claveSolicitud = `${rendicionId}:${revision}`
  const cargando = solicitudFinalizada !== claveSolicitud
  useEffect(() => { const controlador = new AbortController(); void obtenerRendicionCaja(rendicionId, controlador.signal).then((dato) => { setRendicion(dato); setError(null) }).catch((errorActual: unknown) => { if (!controlador.signal.aborted) setError(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible cargar la rendición.') }).finally(() => { if (!controlador.signal.aborted) setSolicitudFinalizada(claveSolicitud) }); return () => controlador.abort() }, [claveSolicitud, rendicionId])
  const cargarAuditoria = useCallback((consulta: ConsultaAuditoria, signal?: AbortSignal) => listarAuditoriaCaja('RENDICION_REPARTIDOR', rendicionId, consulta, signal), [rendicionId])
  const aprobar = async () => { if (!rendicion) return; if (motivo.trim().length < 5) { setErrorMotivo('El motivo debe contener al menos 5 caracteres.'); return } setProcesando(true); setErrorAccion(null); try { const dato = await aprobarRendicionCaja(rendicion.id, { version: rendicion.version, motivo: motivo.trim() }); setRendicion(dato); setMostrarAprobacion(false); setMotivo(''); setMensajeExito(`La rendición ${dato.numero} quedó aprobada.`); setRevision((valor) => valor + 1) } catch (errorActual: unknown) { setMostrarAprobacion(false); setErrorAccion(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible aprobar la rendición.') } finally { setProcesando(false) } }
  if (cargando && !rendicion) return <section className={styles.pagina}><p role="status">Cargando rendición…</p></section>
  if (error || !rendicion) return <section className={styles.pagina}><CajaBreadcrumb seccion="Rendiciones" actual="Detalle" onNavegar={onNavegar} /><div className={styles.alertaError} role="alert"><p>{error ?? 'La rendición no está disponible.'}</p><button type="button" onClick={() => setRevision((valor) => valor + 1)}>Reintentar</button></div></section>
  return <section className={styles.pagina} aria-labelledby="titulo-rendicion"><CajaBreadcrumb seccion="Rendiciones" actual={rendicion.numero} onNavegar={onNavegar} /><header className={styles.cabeceraDetalle}><div><p className={styles.sobretitulo}>Rendición de repartidor</p><h1 id="titulo-rendicion">{rendicion.numero}</h1><p>{rendicion.repartidorNombre} · {rendicion.referenciaOperativa}</p><span className={`${styles.estado} ${claseEstado(rendicion.estado)}`}>{etiquetasEstadoRendicion[rendicion.estado]}</span></div><div className={styles.accionesCabecera}><button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`/caja/turnos/${rendicion.turnoDestinoId}`)}>Ver turno receptor</button>{rendicion.movimientoIngresoId && <button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`/caja/movimientos/${rendicion.movimientoIngresoId}`)}>Ver ingreso</button>}{permisos.includes('CAJA.INCIDENCIAS.CREAR') && <button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`/caja/incidencias/nueva?entidadTipo=RENDICION_REPARTIDOR&entidadId=${rendicion.id}`)}><IconoAccion nombre="agregar" />Reportar incidencia</button>}{permisos.includes('CAJA.RENDICIONES.APROBAR') && ['PENDIENTE_APROBACION', 'INVESTIGACION'].includes(rendicion.estado) && <button className={styles.botonPrincipal} type="button" onClick={() => setMostrarAprobacion(true)}><IconoAccion nombre="guardar" />Aprobar rendición</button>}</div></header>
    <div className={styles.grillaDetalle}><article className={styles.tarjetaDetalle}><h2>Liquidación</h2><dl><div><dt>Fondo para cambio</dt><dd>{formatearCentavos(rendicion.fondoCambioCentavos)}</dd></div><div><dt>Cobrado</dt><dd>{formatearCentavos(rendicion.cobradoCentavos)}</dd></div><div><dt>Cambio entregado</dt><dd>{formatearCentavos(rendicion.cambioEntregadoCentavos)}</dd></div><div><dt>Esperado</dt><dd>{formatearCentavos(rendicion.esperadoCentavos)}</dd></div><div><dt>Efectivo entregado</dt><dd><strong>{formatearCentavos(rendicion.efectivoEntregadoCentavos)}</strong></dd></div><div><dt>Diferencia</dt><dd><strong>{formatearCentavos(rendicion.diferenciaCentavos)}</strong></dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Operación</h2><dl><div><dt>Fecha de negocio</dt><dd>{formatearFecha(rendicion.fechaNegocio)}</dd></div><div><dt>Entregas</dt><dd>{rendicion.cantidadEntregas}</dd></div><div><dt>Turno receptor</dt><dd>{rendicion.turnoDestinoNumero ?? rendicion.turnoDestinoId}</dd></div><div><dt>Caja</dt><dd>{rendicion.cajaDestino?.nombre ?? 'Caja de ventas'}</dd></div><div><dt>Recibida</dt><dd>{formatearFechaHora(rendicion.recibidoEn)}</dd></div><div><dt>Aprobada</dt><dd>{formatearFechaHora(rendicion.aprobadoEn)}</dd></div><div className={styles.datoCompleto}><dt>Explicación</dt><dd>{rendicion.explicacion ?? 'Sin diferencia reportada'}</dd></div></dl></article></div>
    <EvidenciasCaja entidadTipo="RENDICION_REPARTIDOR" entidadId={rendicion.id} permisos={permisos} revision={revision} onCambio={() => setRevision((valor) => valor + 1)} />{permisos.includes('CAJA.RENDICIONES.VER_AUDITORIA') && <PistaAuditoria claveEntidad={`rendicion-${rendicion.id}`} descripcion="Recepción, diferencia, aprobación y movimiento de ingreso de la rendición." etiquetasOperacion={{ REGISTRAR: 'Registro', APROBAR: 'Aprobación', ADJUNTAR_EVIDENCIA: 'Evidencia adjunta' }} cargarEventos={cargarAuditoria} revision={revision} />}
    <ModalEstado abierto={mostrarAprobacion} tipo="informacion" titulo="Aprobar rendición" mensaje={<CampoMotivo id="motivo-aprobar-rendicion" valor={motivo} error={errorMotivo} onChange={(valor) => { setMotivo(valor); setErrorMotivo(null) }} />} textoAccionPrincipal="Aprobar rendición" onAccionPrincipal={() => void aprobar()} textoAccionSecundaria="Cancelar" onAccionSecundaria={() => setMostrarAprobacion(false)} onCerrar={() => setMostrarAprobacion(false)} cargando={procesando} /><ModalEstado abierto={Boolean(mensajeExito)} tipo="exito" titulo="Rendición aprobada" mensaje={mensajeExito ?? ''} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => setMensajeExito(null)} onCerrar={() => setMensajeExito(null)} /><ModalEstado abierto={Boolean(errorAccion)} tipo="error" titulo="No se pudo completar la acción" mensaje={errorAccion ?? ''} textoAccionPrincipal="Entendido" onAccionPrincipal={() => setErrorAccion(null)} onCerrar={() => setErrorAccion(null)} />
  </section>
}

export function ConciliacionDetalleView({ conciliacionId, permisos, onNavegar }: Props & { conciliacionId: string }) {
  const [conciliacion, setConciliacion] = useState<ConciliacionCaja | null>(null)
  const [solicitudFinalizada, setSolicitudFinalizada] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [accion, setAccion] = useState<AccionConciliacion>(null)
  const [motivo, setMotivo] = useState('')
  const [errorMotivo, setErrorMotivo] = useState<string | null>(null)
  const [procesando, setProcesando] = useState(false)
  const [mensajeExito, setMensajeExito] = useState<string | null>(null)
  const [errorAccion, setErrorAccion] = useState<string | null>(null)
  const [revision, setRevision] = useState(0)
  const claveSolicitud = `${conciliacionId}:${revision}`
  const cargando = solicitudFinalizada !== claveSolicitud
  useEffect(() => { const controlador = new AbortController(); void obtenerConciliacionCaja(conciliacionId, controlador.signal).then((dato) => { setConciliacion(dato); setError(null) }).catch((errorActual: unknown) => { if (!controlador.signal.aborted) setError(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible cargar la conciliación.') }).finally(() => { if (!controlador.signal.aborted) setSolicitudFinalizada(claveSolicitud) }); return () => controlador.abort() }, [claveSolicitud, conciliacionId])
  const cargarAuditoria = useCallback((consulta: ConsultaAuditoria, signal?: AbortSignal) => listarAuditoriaCaja('CONCILIACION_CAJA', conciliacionId, consulta, signal), [conciliacionId])
  const ejecutar = async () => { if (!conciliacion || !accion) return; if (motivo.trim().length < 5) { setErrorMotivo('El motivo debe contener al menos 5 caracteres.'); return } setProcesando(true); setErrorAccion(null); try { const dato = accion === 'confirmar' ? await confirmarConciliacionCaja(conciliacion.id, { version: conciliacion.version, motivo: motivo.trim() }) : await reabrirConciliacionCaja(conciliacion.id, { version: conciliacion.version, motivo: motivo.trim() }); setConciliacion(dato); setAccion(null); setMotivo(''); setMensajeExito(`La conciliación ${dato.numero} quedó ${etiquetasEstadoConciliacion[dato.estado].toLowerCase()}.`); setRevision((valor) => valor + 1) } catch (errorActual: unknown) { setAccion(null); setErrorAccion(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible actualizar la conciliación.') } finally { setProcesando(false) } }
  if (cargando && !conciliacion) return <section className={styles.pagina}><p role="status">Cargando conciliación…</p></section>
  if (error || !conciliacion) return <section className={styles.pagina}><CajaBreadcrumb seccion="Conciliaciones" actual="Detalle" onNavegar={onNavegar} /><div className={styles.alertaError} role="alert"><p>{error ?? 'La conciliación no está disponible.'}</p><button type="button" onClick={() => setRevision((valor) => valor + 1)}>Reintentar</button></div></section>
  const rutaOrigen = conciliacion.tipo === 'TURNO' ? '/caja/turnos' : conciliacion.tipo === 'DEPOSITO' ? '/caja/depositos' : '/caja/rendiciones'
  return <section className={styles.pagina} aria-labelledby="titulo-conciliacion"><CajaBreadcrumb seccion="Conciliaciones" actual={conciliacion.numero} onNavegar={onNavegar} /><header className={styles.cabeceraDetalle}><div><p className={styles.sobretitulo}>Conciliación formal</p><h1 id="titulo-conciliacion">{conciliacion.numero}</h1><p>{etiquetasTipoConciliacion[conciliacion.tipo]} · {conciliacion.referenciaNumero}</p><span className={`${styles.estado} ${claseEstado(conciliacion.estado)}`}>{etiquetasEstadoConciliacion[conciliacion.estado]}</span></div><div className={styles.accionesCabecera}><button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`${rutaOrigen}/${conciliacion.referenciaId}`)}>Ver origen</button>{permisos.includes('CAJA.INCIDENCIAS.CREAR') && <button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`/caja/incidencias/nueva?entidadTipo=CONCILIACION_CAJA&entidadId=${conciliacion.id}`)}><IconoAccion nombre="agregar" />Reportar incidencia</button>}{permisos.includes('CAJA.CONCILIACIONES.CONFIRMAR') && ['PENDIENTE', 'PARCIAL', 'REABIERTA'].includes(conciliacion.estado) && <button className={styles.botonPrincipal} type="button" onClick={() => setAccion('confirmar')}><IconoAccion nombre="guardar" />Confirmar conciliación</button>}{permisos.includes('CAJA.CONCILIACIONES.REABRIR') && ['CONCILIADA', 'DIFERENCIA'].includes(conciliacion.estado) && <button className={styles.botonPeligro} type="button" onClick={() => setAccion('reabrir')}><IconoAccion nombre="estado" />Reabrir conciliación</button>}</div></header>
    <div className={styles.grillaDetalle}><article className={styles.tarjetaDetalle}><h2>Comparación</h2><dl><div><dt>Esperado</dt><dd>{formatearCentavos(conciliacion.esperadoCentavos)}</dd></div><div><dt>Registrado</dt><dd>{formatearCentavos(conciliacion.registradoCentavos)}</dd></div><div><dt>Diferencia</dt><dd><strong>{formatearCentavos(conciliacion.diferenciaCentavos)}</strong></dd></div><div><dt>Estado</dt><dd>{etiquetasEstadoConciliacion[conciliacion.estado]}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Control</h2><dl><div><dt>Fecha de negocio</dt><dd>{formatearFecha(conciliacion.fechaNegocio)}</dd></div><div><dt>Tipo</dt><dd>{etiquetasTipoConciliacion[conciliacion.tipo]}</dd></div><div><dt>Referencia</dt><dd>{conciliacion.referenciaNumero}</dd></div><div><dt>Conciliada</dt><dd>{formatearFechaHora(conciliacion.conciliadoEn)}</dd></div><div><dt>Reabierta</dt><dd>{formatearFechaHora(conciliacion.reabiertoEn)}</dd></div><div className={styles.datoCompleto}><dt>Observación</dt><dd>{conciliacion.observacion ?? 'Sin observación'}</dd></div><div className={styles.datoCompleto}><dt>Motivo de reapertura</dt><dd>{conciliacion.motivoReapertura ?? 'No aplica'}</dd></div></dl></article></div>
    <EvidenciasCaja entidadTipo="CONCILIACION_CAJA" entidadId={conciliacion.id} permisos={permisos} revision={revision} onCambio={() => setRevision((valor) => valor + 1)} />{permisos.includes('CAJA.CONCILIACIONES.VER_AUDITORIA') && <PistaAuditoria claveEntidad={`conciliacion-${conciliacion.id}`} descripcion="Creación, confirmación, diferencias, reapertura y evidencias de la conciliación." etiquetasOperacion={{ CREAR: 'Creación', CONFIRMAR: 'Confirmación', REABRIR: 'Reapertura', ADJUNTAR_EVIDENCIA: 'Evidencia adjunta' }} cargarEventos={cargarAuditoria} revision={revision} />}
    <ModalEstado abierto={Boolean(accion)} tipo={accion === 'reabrir' ? 'advertencia' : 'informacion'} titulo={accion === 'reabrir' ? 'Reabrir conciliación' : 'Confirmar conciliación'} mensaje={<CampoMotivo id="motivo-conciliacion" valor={motivo} error={errorMotivo} onChange={(valor) => { setMotivo(valor); setErrorMotivo(null) }} />} textoAccionPrincipal={accion === 'reabrir' ? 'Reabrir conciliación' : 'Confirmar conciliación'} onAccionPrincipal={() => void ejecutar()} textoAccionSecundaria="Cancelar" onAccionSecundaria={() => setAccion(null)} onCerrar={() => setAccion(null)} cargando={procesando} /><ModalEstado abierto={Boolean(mensajeExito)} tipo="exito" titulo="Conciliación actualizada" mensaje={mensajeExito ?? ''} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => setMensajeExito(null)} onCerrar={() => setMensajeExito(null)} /><ModalEstado abierto={Boolean(errorAccion)} tipo="error" titulo="No se pudo completar la acción" mensaje={errorAccion ?? ''} textoAccionPrincipal="Entendido" onAccionPrincipal={() => setErrorAccion(null)} onCerrar={() => setErrorAccion(null)} />
  </section>
}

export function ConsolidacionDetalleView({ consolidacionId, permisos, onNavegar }: Props & { consolidacionId: string }) {
  const [consolidacion, setConsolidacion] = useState<ConsolidacionDiariaCaja | null>(null)
  const [solicitudFinalizada, setSolicitudFinalizada] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [accion, setAccion] = useState<AccionConsolidacion>(null)
  const [motivo, setMotivo] = useState('')
  const [errorMotivo, setErrorMotivo] = useState<string | null>(null)
  const [procesando, setProcesando] = useState(false)
  const [mensajeExito, setMensajeExito] = useState<string | null>(null)
  const [errorAccion, setErrorAccion] = useState<string | null>(null)
  const [revision, setRevision] = useState(0)
  const claveSolicitud = `${consolidacionId}:${revision}`
  const cargando = solicitudFinalizada !== claveSolicitud
  useEffect(() => { const controlador = new AbortController(); void obtenerConsolidacionCaja(consolidacionId, controlador.signal).then((dato) => { setConsolidacion(dato); setError(null) }).catch((errorActual: unknown) => { if (!controlador.signal.aborted) setError(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible cargar la consolidación.') }).finally(() => { if (!controlador.signal.aborted) setSolicitudFinalizada(claveSolicitud) }); return () => controlador.abort() }, [claveSolicitud, consolidacionId])
  const cargarAuditoria = useCallback((consulta: ConsultaAuditoria, signal?: AbortSignal) => listarAuditoriaCaja('CONSOLIDACION_DIARIA_CAJA', consolidacionId, consulta, signal), [consolidacionId])
  const ejecutar = async () => { if (!consolidacion || !accion) return; if (motivo.trim().length < 5) { setErrorMotivo('El motivo debe contener al menos 5 caracteres.'); return } setProcesando(true); setErrorAccion(null); try { const dato = accion === 'aprobar' ? await aprobarConsolidacionCaja(consolidacion.id, { version: consolidacion.version, motivo: motivo.trim() }) : await reabrirConsolidacionCaja(consolidacion.id, { version: consolidacion.version, motivo: motivo.trim() }); setConsolidacion(dato); setAccion(null); setMotivo(''); setMensajeExito(`La consolidación ${dato.numero} quedó ${etiquetasEstadoConsolidacion[dato.estado].toLowerCase()}.`); setRevision((valor) => valor + 1) } catch (errorActual: unknown) { setAccion(null); setErrorAccion(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible actualizar la consolidación.') } finally { setProcesando(false) } }
  if (cargando && !consolidacion) return <section className={styles.pagina}><p role="status">Cargando consolidación…</p></section>
  if (error || !consolidacion) return <section className={styles.pagina}><CajaBreadcrumb seccion="Consolidaciones" actual="Detalle" onNavegar={onNavegar} /><div className={styles.alertaError} role="alert"><p>{error ?? 'La consolidación no está disponible.'}</p><button type="button" onClick={() => setRevision((valor) => valor + 1)}>Reintentar</button></div></section>
  return <section className={styles.pagina} aria-labelledby="titulo-consolidacion"><CajaBreadcrumb seccion="Consolidaciones" actual={consolidacion.numero} onNavegar={onNavegar} /><header className={styles.cabeceraDetalle}><div><p className={styles.sobretitulo}>Consolidación diaria</p><h1 id="titulo-consolidacion">{consolidacion.numero}</h1><p>{consolidacion.sucursal?.nombre ?? 'Sucursal activa'} · {formatearFecha(consolidacion.fechaNegocio)} · Versión {consolidacion.versionConsolidacion}</p><span className={`${styles.estado} ${claseEstado(consolidacion.estado)}`}>{etiquetasEstadoConsolidacion[consolidacion.estado]}</span></div><div className={styles.accionesCabecera}>{permisos.includes('CAJA.INCIDENCIAS.CREAR') && <button className={styles.botonSecundario} type="button" onClick={() => onNavegar(`/caja/incidencias/nueva?entidadTipo=CONSOLIDACION_DIARIA_CAJA&entidadId=${consolidacion.id}`)}><IconoAccion nombre="agregar" />Reportar incidencia</button>}{permisos.includes('CAJA.CONSOLIDACIONES.APROBAR') && ['PENDIENTE_APROBACION', 'INVESTIGACION'].includes(consolidacion.estado) && <button className={styles.botonPrincipal} type="button" onClick={() => setAccion('aprobar')}><IconoAccion nombre="guardar" />Aprobar consolidación</button>}{permisos.includes('CAJA.CONSOLIDACIONES.REABRIR') && consolidacion.estado === 'APROBADA' && <button className={styles.botonPeligro} type="button" onClick={() => setAccion('reabrir')}><IconoAccion nombre="estado" />Reabrir consolidación</button>}</div></header>
    <div className={styles.grillaDetalle}><article className={styles.tarjetaDetalle}><h2>Turnos y operación</h2><dl><div><dt>Turnos</dt><dd>{consolidacion.turnosCerrados} de {consolidacion.totalTurnos} cerrados</dd></div><div><dt>Fondo inicial</dt><dd>{formatearCentavos(consolidacion.fondoInicialCentavos)}</dd></div><div><dt>Ingresos</dt><dd>{formatearCentavos(consolidacion.ingresosCentavos)}</dd></div><div><dt>Egresos</dt><dd>{formatearCentavos(consolidacion.egresosCentavos)}</dd></div><div><dt>Saldo teórico</dt><dd><strong>{formatearCentavos(consolidacion.saldoTeoricoCentavos)}</strong></dd></div><div><dt>Efectivo declarado</dt><dd>{formatearCentavos(consolidacion.efectivoDeclaradoCentavos)}</dd></div><div><dt>Diferencia de cierres</dt><dd>{formatearCentavos(consolidacion.diferenciaCierresCentavos)}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Rendiciones y depósitos</h2><dl><div><dt>Rendido</dt><dd>{formatearCentavos(consolidacion.rendidoCentavos)}</dd></div><div><dt>Depósito preparado</dt><dd>{formatearCentavos(consolidacion.depositoPreparadoCentavos)}</dd></div><div><dt>Depositado</dt><dd>{formatearCentavos(consolidacion.depositadoCentavos)}</dd></div><div><dt>Diferencia de depósitos</dt><dd>{formatearCentavos(consolidacion.diferenciaDepositoCentavos)}</dd></div><div><dt>Incidencias abiertas</dt><dd>{consolidacion.incidenciasAbiertas}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Control</h2><dl><div><dt>Generada</dt><dd>{formatearFechaHora(consolidacion.generadoEn)}</dd></div><div><dt>Aprobada</dt><dd>{formatearFechaHora(consolidacion.aprobadoEn)}</dd></div><div><dt>Reabierta</dt><dd>{formatearFechaHora(consolidacion.reabiertoEn)}</dd></div><div className={styles.datoCompleto}><dt>Motivo de reapertura</dt><dd>{consolidacion.motivoReapertura ?? 'No aplica'}</dd></div></dl></article></div>
    <EvidenciasCaja entidadTipo="CONSOLIDACION_DIARIA_CAJA" entidadId={consolidacion.id} permisos={permisos} revision={revision} onCambio={() => setRevision((valor) => valor + 1)} />{permisos.includes('CAJA.CONSOLIDACIONES.VER_AUDITORIA') && <PistaAuditoria claveEntidad={`consolidacion-${consolidacion.id}`} descripcion="Generación, aprobación, reapertura, versiones y evidencias de la consolidación diaria." etiquetasOperacion={{ GENERAR: 'Generación', APROBAR: 'Aprobación', REABRIR: 'Reapertura', ADJUNTAR_EVIDENCIA: 'Evidencia adjunta' }} cargarEventos={cargarAuditoria} revision={revision} />}
    <ModalEstado abierto={Boolean(accion)} tipo={accion === 'reabrir' ? 'advertencia' : 'informacion'} titulo={accion === 'reabrir' ? 'Reabrir consolidación' : 'Aprobar consolidación'} mensaje={<CampoMotivo id="motivo-consolidacion" valor={motivo} error={errorMotivo} onChange={(valor) => { setMotivo(valor); setErrorMotivo(null) }} />} textoAccionPrincipal={accion === 'reabrir' ? 'Reabrir consolidación' : 'Aprobar consolidación'} onAccionPrincipal={() => void ejecutar()} textoAccionSecundaria="Cancelar" onAccionSecundaria={() => setAccion(null)} onCerrar={() => setAccion(null)} cargando={procesando} /><ModalEstado abierto={Boolean(mensajeExito)} tipo="exito" titulo="Consolidación actualizada" mensaje={mensajeExito ?? ''} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => setMensajeExito(null)} onCerrar={() => setMensajeExito(null)} /><ModalEstado abierto={Boolean(errorAccion)} tipo="error" titulo="No se pudo completar la acción" mensaje={errorAccion ?? ''} textoAccionPrincipal="Entendido" onAccionPrincipal={() => setErrorAccion(null)} onCerrar={() => setErrorAccion(null)} />
  </section>
}
