import { useEffect, useState } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { aprobarPrecio, obtenerPrecio } from '../comercial-api'
import type { EstadoPrecio, PrecioProducto } from '../comercial.types'
import { AccionConMotivoModal } from './accion-con-motivo-modal'
import { ComercialAuditoria } from './comercial-auditoria'
import { ComercialBreadcrumb } from './comercial-breadcrumb'
import styles from './comercial.module.css'

const etiquetas: Record<EstadoPrecio, string> = { BORRADOR: 'Borrador', VIGENTE: 'Vigente', INACTIVO: 'Inactivo' }
const moneda = (x: number, decimales = 2) => new Intl.NumberFormat('es-GT', { style: 'currency', currency: 'GTQ', minimumFractionDigits: decimales, maximumFractionDigits: decimales }).format(x)
const fecha = (x: string | null) => x ? new Intl.DateTimeFormat('es-GT', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Guatemala' }).format(new Date(x)) : 'No aplica'

export function PrecioDetalleView({ precioId, permisos, onNavegar }: { precioId: string; permisos: readonly string[]; onNavegar: (ruta: string) => void }) {
  const [precio, setPrecio] = useState<PrecioProducto | null>(null); const [error, setError] = useState<string | null>(null); const [revision, setRevision] = useState(0); const [aprobar, setAprobar] = useState(false); const [exito, setExito] = useState(false)
  useEffect(() => { const c = new AbortController(); void obtenerPrecio(precioId, c.signal).then((x) => { setPrecio(x); setError(null) }).catch((e: unknown) => { if (!c.signal.aborted) setError(e instanceof ErrorApi ? e.message : 'No fue posible cargar el precio.') }); return () => c.abort() }, [precioId, revision])
  if (error) return <section className={styles.pagina}><ComercialBreadcrumb seccion="Precios" rutaListado="/comercial/precios" actual="Detalle" onNavegar={onNavegar} /><div className={styles.estadoVacio} role="alert"><h1>No fue posible cargar el precio</h1><p>{error}</p><button type="button" onClick={() => setRevision((x) => x + 1)}>Reintentar</button></div></section>
  if (!precio) return <section className={styles.pagina} aria-busy="true"><ComercialBreadcrumb seccion="Precios" rutaListado="/comercial/precios" actual="Detalle" onNavegar={onNavegar} /><div className={styles.estadoVacio}><h1>Cargando precio</h1></div></section>
  const confirmar = async (motivo: string) => { const x = await aprobarPrecio(precio.id, precio.version, motivo); setPrecio(x); setAprobar(false); setExito(true); setRevision((r) => r + 1) }
  return <><section className={styles.pagina} aria-labelledby="titulo-detalle-precio"><ComercialBreadcrumb seccion="Precios" rutaListado="/comercial/precios" actual="Detalle de precio" onNavegar={onNavegar} /><header className={styles.cabeceraDetalle}><div><p className={styles.sobretitulo}>{precio.codigo}</p><h1 id="titulo-detalle-precio">{precio.producto}</h1><span className={`${styles.estado} ${precio.estado === 'VIGENTE' ? styles.estadoActivo : styles.estadoInactivo}`}>{etiquetas[precio.estado]}</span></div>{precio.estado === 'BORRADOR' && permisos.includes('COMERCIAL.PRECIOS.APROBAR') && <div className={styles.accionesCabecera}><button className={styles.botonEstado} type="button" onClick={() => setAprobar(true)}><IconoAccion nombre="estado" />Aprobar precio</button></div>}</header><div className={styles.grillaDetalle}><article className={styles.tarjetaDetalle}><h2>Precio calculado</h2><dl><div><dt>Costo promedio</dt><dd>{moneda(precio.costoPromedio, 4)}</dd></div><div><dt>Costo de reposición</dt><dd>{moneda(precio.costoReposicion, 4)}</dd></div><div><dt>Costo base</dt><dd><strong>{moneda(precio.costoBase, 4)}</strong></dd></div><div><dt>Margen</dt><dd>{precio.margenPorcentaje}%</dd></div><div><dt>Precio sugerido</dt><dd>{moneda(precio.precioSugerido)}</dd></div><div><dt>Precio de venta</dt><dd><strong>{moneda(precio.precioVenta)}</strong></dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Control y vigencia</h2><dl><div className={styles.datoCompleto}><dt>Política aplicada</dt><dd>{precio.politicaMargen}</dd></div><div><dt>Vigente desde</dt><dd>{fecha(precio.vigenteDesde)}</dd></div><div><dt>Vigente hasta</dt><dd>{fecha(precio.vigenteHasta)}</dd></div><div className={styles.datoCompleto}><dt>Motivo</dt><dd>{precio.motivo}</dd></div></dl></article></div><div className={styles.notaInformativa}><strong>Lectura del cálculo</strong><span>Se tomó {precio.costoReposicion >= precio.costoPromedio ? 'el costo de reposición' : 'el costo promedio ponderado'} como base por ser el mayor. La aprobación volverá este precio vigente y cerrará el precio anterior del producto.</span></div>{permisos.includes('COMERCIAL.PRECIOS.VER_AUDITORIA') && permisos.includes('COMERCIAL.PRECIOS.VER') && <ComercialAuditoria recurso="precios" entidadId={precio.id} revision={revision} />}</section><AccionConMotivoModal abierto={aprobar} titulo="Aprobar precio" mensaje={`Se habilitará ${moneda(precio.precioVenta)} como precio vigente de ${precio.producto}.`} textoAccion="Aprobar precio" onCerrar={() => setAprobar(false)} onConfirmar={confirmar} /><ModalEstado abierto={exito} tipo="exito" titulo="Precio aprobado" mensaje="El precio quedó vigente y ya puede utilizarse en nuevas ventas." textoAccionPrincipal="Entendido" onAccionPrincipal={() => setExito(false)} onCerrar={() => setExito(false)} /></>
}
