import type { EmpleadoDisponibleUsuario, RolDisponibleUsuario, Usuario } from '../usuario.types'
import type { DatosFormularioUsuario, ErroresFormularioUsuario } from '../validacion-usuario'
import { SelectorRolesUsuario } from './selector-roles-usuario'
import styles from '../../roles/components/rol-formulario.module.css'
import usuarioStyles from './usuario-formulario.module.css'
type Props = { datos: DatosFormularioUsuario; errores: ErroresFormularioUsuario; empleados: readonly EmpleadoDisponibleUsuario[]; roles: readonly RolDisponibleUsuario[]; usuario?: Usuario; deshabilitado: boolean; onChange: (datos: DatosFormularioUsuario) => void }
export function UsuarioFormularioCampos({ datos, errores, empleados, roles, usuario, deshabilitado, onChange }: Props) {
  return <><fieldset disabled={deshabilitado}><legend>Información de la cuenta</legend><div className={styles.grillaDos}><div className={styles.campo}><label htmlFor="empleadoId">Empleado <span aria-hidden="true">*</span></label>{usuario ? <div className={usuarioStyles.empleadoSeleccionado}><strong>{usuario.empleadoNombre}</strong><span>{usuario.empleadoCodigo} · {usuario.empleadoCorreo}</span></div> : <select id="empleadoId" value={datos.empleadoId} aria-invalid={Boolean(errores.empleadoId)} aria-describedby={errores.empleadoId ? 'error-empleadoId' : 'ayuda-empleadoId'} onChange={(evento) => onChange({ ...datos, empleadoId: evento.target.value })}><option value="">Selecciona un empleado</option>{empleados.map((empleado) => <option key={empleado.id} value={empleado.id}>{empleado.codigo} — {empleado.nombre} ({empleado.correo})</option>)}</select>}{errores.empleadoId ? <small id="error-empleadoId" className={styles.errorCampo}>{errores.empleadoId}</small> : !usuario && <small id="ayuda-empleadoId" className={styles.ayudaCampo}>Solo aparecen empleados activos, con correo y sin una cuenta existente.</small>}</div><div className={styles.campo}><label htmlFor="nombreUsuario">Nombre de usuario <span aria-hidden="true">*</span></label><input id="nombreUsuario" value={datos.nombreUsuario} maxLength={50} autoComplete="off" aria-invalid={Boolean(errores.nombreUsuario)} aria-describedby={errores.nombreUsuario ? 'error-nombreUsuario' : 'ayuda-nombreUsuario'} onChange={(evento) => onChange({ ...datos, nombreUsuario: evento.target.value.toUpperCase() })} />{errores.nombreUsuario ? <small id="error-nombreUsuario" className={styles.errorCampo}>{errores.nombreUsuario}</small> : <small id="ayuda-nombreUsuario" className={styles.ayudaCampo}>Letras, números, punto, guion o guion bajo.</small>}</div></div><p className={usuarioStyles.avisoCorreo}>{usuario ? 'Los cambios de roles revocarán las sesiones abiertas del usuario.' : 'Al registrar la cuenta se enviará al correo del empleado un enlace de un solo uso para crear su contraseña.'}</p></fieldset><SelectorRolesUsuario roles={roles} seleccionados={datos.roles} errores={errores} deshabilitado={deshabilitado} onChange={(seleccionados) => onChange({ ...datos, roles: seleccionados })} /></>
}
