import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { actualizarUsuario, asignarRolesUsuario, obtenerOpcionesUsuario, obtenerUsuario } from '../usuario-api'
import type { OpcionesFormularioUsuario, Usuario } from '../usuario.types'
import { fechaVigenciaApi, fechaVigenciaFormulario, validarFormularioUsuario, type DatosFormularioUsuario, type ErroresFormularioUsuario } from '../validacion-usuario'
import { UsuarioBreadcrumb } from './usuario-breadcrumb'
import { UsuarioFormularioCampos } from './usuario-formulario-campos'
import styles from '../../roles/components/rol-formulario.module.css'
type Props = { usuarioId: string; onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }
const datosDesdeUsuario = (usuario: Usuario): DatosFormularioUsuario => ({ empleadoId: usuario.empleadoId, nombreUsuario: usuario.nombreUsuario, roles: usuario.roles.map((rol) => ({ rolId: rol.id, vigenteHasta: fechaVigenciaFormulario(rol.vigenteHasta), indefinido: rol.vigenteHasta === null })) })
const normalizarRoles = (datos: DatosFormularioUsuario) => [...datos.roles].sort((a, b) => a.rolId.localeCompare(b.rolId))
export function UsuarioEditarView({ usuarioId, onNavegar, onCambiosPendientes }: Props) {
  const [usuario, setUsuario] = useState<Usuario | null>(null); const [opciones, setOpciones] = useState<OpcionesFormularioUsuario | null>(null); const [datos, setDatos] = useState<DatosFormularioUsuario | null>(null); const [iniciales, setIniciales] = useState<DatosFormularioUsuario | null>(null); const [errores, setErrores] = useState<ErroresFormularioUsuario>({}); const [errorGeneral, setErrorGeneral] = useState<string | null>(null); const [guardando, setGuardando] = useState(false); const [exito, setExito] = useState(false); const [sinCambios, setSinCambios] = useState(false); const [revision, setRevision] = useState(0); const formularioRef = useRef<HTMLFormElement>(null)
  useEffect(() => { const controlador = new AbortController(); void Promise.all([obtenerUsuario(usuarioId, controlador.signal), obtenerOpcionesUsuario(controlador.signal)]).then(([respuestaUsuario, respuestaOpciones]) => { const valores = datosDesdeUsuario(respuestaUsuario); setUsuario(respuestaUsuario); setOpciones(respuestaOpciones); setDatos(valores); setIniciales(valores); setErrorGeneral(null) }).catch((error: unknown) => { if (!controlador.signal.aborted) setErrorGeneral(error instanceof ErrorApi ? error.message : 'No fue posible cargar el usuario.') }); return () => controlador.abort() }, [revision, usuarioId])
  const hayCambios = useMemo(() => Boolean(datos && iniciales && (datos.nombreUsuario !== iniciales.nombreUsuario || JSON.stringify(normalizarRoles(datos)) !== JSON.stringify(normalizarRoles(iniciales)))), [datos, iniciales]); useEffect(() => onCambiosPendientes(hayCambios && !exito), [exito, hayCambios, onCambiosPendientes]); useEffect(() => () => onCambiosPendientes(false), [onCambiosPendientes])
  const guardar = async (evento: FormEvent<HTMLFormElement>) => { evento.preventDefault(); if (!usuario || !datos || !iniciales) return; const siguientes = validarFormularioUsuario(datos, false); setErrores(siguientes); if (siguientes.nombreUsuario || siguientes.roles || siguientes.vigencias) { const primerCampo = siguientes.nombreUsuario ? 'nombreUsuario' : siguientes.roles ? undefined : `vigencia-${Object.keys(siguientes.vigencias ?? {})[0]}`; if (primerCampo) formularioRef.current?.querySelector<HTMLElement>(`#${primerCampo}`)?.focus(); return } if (!hayCambios) { setSinCambios(true); return } setGuardando(true); setErrorGeneral(null); try { let actualizado = usuario; if (datos.nombreUsuario !== iniciales.nombreUsuario) actualizado = await actualizarUsuario(usuario.id, { version: actualizado.version, nombreUsuario: datos.nombreUsuario.trim().toUpperCase() }); if (JSON.stringify(normalizarRoles(datos)) !== JSON.stringify(normalizarRoles(iniciales))) actualizado = await asignarRolesUsuario(usuario.id, { version: actualizado.version, roles: datos.roles.map((rol) => ({ rolId: rol.rolId, vigenteHasta: fechaVigenciaApi(rol.vigenteHasta) })) }); setUsuario(actualizado); onCambiosPendientes(false); setExito(true) } catch (error: unknown) { if (error instanceof ErrorApi) { setErrorGeneral(error.message); const erroresApi = Object.fromEntries(error.detalles.map((detalle) => [detalle.campo, detalle.mensaje])) as ErroresFormularioUsuario; if (Object.keys(erroresApi).length) setErrores(erroresApi) } else setErrorGeneral('No fue posible actualizar el usuario.') } finally { setGuardando(false) } }
  if (!usuario || !datos || !opciones) return <section className={styles.estadoCargaFormulario}><UsuarioBreadcrumb actual="Editar usuario" onNavegar={onNavegar} /><h1>{errorGeneral ? 'No se pudo cargar el usuario' : 'Cargando usuario…'}</h1><p>{errorGeneral ?? 'Estamos preparando la información.'}</p>{errorGeneral && <button type="button" onClick={() => setRevision((valor) => valor + 1)}>Reintentar</button>}</section>
  return <section className={styles.paginaFormulario}><header className={styles.encabezadoPagina}><div><UsuarioBreadcrumb actual="Editar usuario" onNavegar={onNavegar} /><h1>Editar usuario</h1></div><span className={styles.indicadorFormulario}>{usuario.nombreUsuario}</span></header>{errorGeneral && <div className={styles.alertaError} role="alert"><span>!</span><p>{errorGeneral}</p></div>}<form ref={formularioRef} className={styles.formulario} onSubmit={(evento) => void guardar(evento)} noValidate><UsuarioFormularioCampos datos={datos} errores={errores} empleados={[]} roles={opciones.roles} usuario={usuario} deshabilitado={guardando || usuario.estado === 'INACTIVO'} onChange={(siguientes) => { setDatos(siguientes); setErrores({}) }} /><div className={styles.accionesFormulario}><p><span aria-hidden="true">*</span> Campos obligatorios</p><div><button className={styles.botonSecundario} type="button" onClick={() => onNavegar('/seguridad/usuarios')} disabled={guardando}><IconoAccion nombre="cancelar" className={styles.iconoBoton} /><span>Cancelar</span></button><button className={styles.botonPrincipal} type="submit" disabled={guardando || usuario.estado === 'INACTIVO'}><IconoAccion nombre="guardar" className={styles.iconoBoton} /><span>{guardando ? 'Guardando cambios…' : 'Guardar cambios'}</span></button></div></div></form><ModalEstado abierto={exito} tipo="exito" titulo="Usuario actualizado" mensaje="La cuenta y sus roles fueron actualizados correctamente." textoAccionPrincipal="Aceptar" onAccionPrincipal={() => onNavegar('/seguridad/usuarios')} onCerrar={() => onNavegar('/seguridad/usuarios')} /><ModalEstado abierto={sinCambios} tipo="informacion" titulo="Sin cambios por guardar" mensaje="No se editó ninguna información del usuario." textoAccionPrincipal="Aceptar" onAccionPrincipal={() => onNavegar('/seguridad/usuarios')} onCerrar={() => setSinCambios(false)} /></section>
}
