import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { crearUsuario, obtenerOpcionesUsuario } from '../usuario-api'
import type { OpcionesFormularioUsuario, UsuarioCreado } from '../usuario.types'
import { fechaVigenciaApi, validarFormularioUsuario, type DatosFormularioUsuario, type ErroresFormularioUsuario } from '../validacion-usuario'
import { UsuarioBreadcrumb } from './usuario-breadcrumb'
import { UsuarioFormularioCampos } from './usuario-formulario-campos'
import styles from '../../roles/components/rol-formulario.module.css'
type Props = { onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }
const iniciales: DatosFormularioUsuario = { empleadoId: '', nombreUsuario: '', roles: [] }
const fechaHora = (valor: string) => new Intl.DateTimeFormat('es-GT', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Guatemala' }).format(new Date(valor))
export function UsuarioCrearView({ onNavegar, onCambiosPendientes }: Props) {
  const [opciones, setOpciones] = useState<OpcionesFormularioUsuario | null>(null); const [datos, setDatos] = useState(iniciales); const [errores, setErrores] = useState<ErroresFormularioUsuario>({}); const [errorGeneral, setErrorGeneral] = useState<string | null>(null); const [guardando, setGuardando] = useState(false); const [exito, setExito] = useState<UsuarioCreado | null>(null); const [correoFallido, setCorreoFallido] = useState(false); const [revision, setRevision] = useState(0); const formularioRef = useRef<HTMLFormElement>(null)
  const tieneCambios = useMemo(() => JSON.stringify(datos) !== JSON.stringify(iniciales), [datos])
  useEffect(() => { const controlador = new AbortController(); void obtenerOpcionesUsuario(controlador.signal).then((respuesta) => { setOpciones(respuesta); setErrorGeneral(null) }).catch((error: unknown) => { if (!controlador.signal.aborted) setErrorGeneral(error instanceof ErrorApi ? error.message : 'No fue posible cargar empleados y roles.') }); return () => controlador.abort() }, [revision])
  useEffect(() => onCambiosPendientes(tieneCambios && !exito && !correoFallido), [correoFallido, exito, onCambiosPendientes, tieneCambios]); useEffect(() => () => onCambiosPendientes(false), [onCambiosPendientes])
  const guardar = async (evento: FormEvent<HTMLFormElement>) => { evento.preventDefault(); const siguientes = validarFormularioUsuario(datos, true); setErrores(siguientes); if (siguientes.empleadoId || siguientes.nombreUsuario || siguientes.roles || siguientes.vigencias) { const primerCampo = siguientes.empleadoId ? 'empleadoId' : siguientes.nombreUsuario ? 'nombreUsuario' : siguientes.roles ? undefined : `vigencia-${Object.keys(siguientes.vigencias ?? {})[0]}`; if (primerCampo) formularioRef.current?.querySelector<HTMLElement>(`#${primerCampo}`)?.focus(); return } setGuardando(true); setErrorGeneral(null); try { const creado = await crearUsuario({ empleadoId: datos.empleadoId, nombreUsuario: datos.nombreUsuario.trim().toUpperCase(), roles: datos.roles.map((rol) => ({ rolId: rol.rolId, vigenteHasta: fechaVigenciaApi(rol.vigenteHasta) })) }); onCambiosPendientes(false); setExito(creado) } catch (error: unknown) { if (error instanceof ErrorApi) { if (error.codigo === 'USUARIO_CREADO_CORREO_NO_ENVIADO') { onCambiosPendientes(false); setCorreoFallido(true) } else { setErrorGeneral(error.message); const erroresApi = Object.fromEntries(error.detalles.map((detalle) => [detalle.campo, detalle.mensaje])) as ErroresFormularioUsuario; if (Object.keys(erroresApi).length) setErrores(erroresApi) } } else setErrorGeneral('No fue posible registrar el usuario.') } finally { setGuardando(false) } }
  if (!opciones) return <section className={styles.estadoCargaFormulario}><UsuarioBreadcrumb actual="Crear usuario" onNavegar={onNavegar} /><h1>{errorGeneral ? 'No se pudo preparar el formulario' : 'Preparando formulario…'}</h1><p>{errorGeneral ?? 'Estamos cargando empleados y roles.'}</p>{errorGeneral && <button type="button" onClick={() => setRevision((valor) => valor + 1)}>Reintentar</button>}</section>
  const puedeCrear = opciones.empleados.length > 0 && opciones.roles.some((rol) => rol.activo)
  return <section className={styles.paginaFormulario}><header className={styles.encabezadoPagina}><div><UsuarioBreadcrumb actual="Crear usuario" onNavegar={onNavegar} /><h1>Crear usuario</h1></div></header>{errorGeneral && <div className={styles.alertaError} role="alert"><span>!</span><p>{errorGeneral}</p></div>}{!puedeCrear && <div className={styles.alertaError} role="alert"><span>!</span><p>Necesitas al menos un empleado disponible y un rol activo para crear una cuenta.</p></div>}<form ref={formularioRef} className={styles.formulario} onSubmit={(evento) => void guardar(evento)} noValidate><UsuarioFormularioCampos datos={datos} errores={errores} empleados={opciones.empleados} roles={opciones.roles} deshabilitado={guardando || !puedeCrear} onChange={(siguientes) => { setDatos(siguientes); setErrores({}) }} /><div className={styles.accionesFormulario}><p><span aria-hidden="true">*</span> Campos obligatorios</p><div><button className={styles.botonSecundario} type="button" onClick={() => onNavegar('/seguridad/usuarios')} disabled={guardando}><IconoAccion nombre="cancelar" className={styles.iconoBoton} /><span>Cancelar</span></button><button className={styles.botonPrincipal} type="submit" disabled={guardando || !puedeCrear}><IconoAccion nombre="guardar" className={styles.iconoBoton} /><span>{guardando ? 'Registrando usuario…' : 'Registrar usuario'}</span></button></div></div></form><ModalEstado abierto={Boolean(exito)} tipo="exito" titulo="Usuario registrado" mensaje={exito ? `La cuenta fue creada y el enlace para definir la contraseña se envió a ${exito.activacionEnviadaA}. El enlace vence el ${fechaHora(exito.activacionExpiraEn)}.` : ''} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => onNavegar('/seguridad/usuarios')} onCerrar={() => onNavegar('/seguridad/usuarios')} /><ModalEstado abierto={correoFallido} tipo="advertencia" titulo="Usuario creado, correo pendiente" mensaje="La cuenta fue creada, pero el correo de activación no pudo enviarse. Desde el detalle del usuario puedes reenviar el enlace." textoAccionPrincipal="Ver listado" onAccionPrincipal={() => onNavegar('/seguridad/usuarios')} onCerrar={() => onNavegar('/seguridad/usuarios')} /></section>
}
