import { solicitarApi } from '../../shared/api/cliente-api'
import { descargarArchivoApi } from '../../shared/api/descargar-archivo-api'
import type { ExportarProductosParametros, GuardarProductoRequest, ListarProductosParametros, OpcionesProducto, Producto, ProductosPaginados } from './producto.types'
type RespuestaApi<T> = { success: true; data: T }
const fechaArchivo = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Guatemala', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
export async function listarProductos(parametros: ListarProductosParametros, signal?: AbortSignal): Promise<ProductosPaginados> { const q = new URLSearchParams({ pagina: String(parametros.pagina), tamanoPagina: String(parametros.tamanoPagina) }); if (parametros.busqueda) q.set('busqueda', parametros.busqueda); if (parametros.producto) q.set('producto', parametros.producto); if (parametros.laboratorios?.length) q.set('laboratorios', parametros.laboratorios.join(',')); if (parametros.presentaciones?.length) q.set('presentaciones', parametros.presentaciones.join(',')); if (parametros.estados?.length) q.set('estados', parametros.estados.join(',')); if (parametros.orden) q.set('orden', parametros.orden); if (parametros.direccion) q.set('direccion', parametros.direccion); return (await solicitarApi<RespuestaApi<ProductosPaginados>>(`/productos?${q.toString()}`, { signal })).data }
export async function obtenerOpcionesProducto(signal?: AbortSignal): Promise<OpcionesProducto> { return (await solicitarApi<RespuestaApi<OpcionesProducto>>('/productos/opciones', { signal })).data }
export async function obtenerProducto(id: string, signal?: AbortSignal): Promise<Producto> { return (await solicitarApi<RespuestaApi<Producto>>(`/productos/${id}`, { signal })).data }
export async function crearProducto(datos: GuardarProductoRequest): Promise<Producto> { return (await solicitarApi<RespuestaApi<Producto>>('/productos', { method: 'POST', datos })).data }
export async function actualizarProducto(id: string, datos: GuardarProductoRequest & { version: number }): Promise<Producto> { return (await solicitarApi<RespuestaApi<Producto>>(`/productos/${id}`, { method: 'PUT', datos })).data }
export async function actualizarImagenProducto(id: string, version: number, imagen: File): Promise<Producto> { const formulario = new FormData(); formulario.append('version', String(version)); formulario.append('imagen', imagen); return (await solicitarApi<RespuestaApi<Producto>>(`/productos/${id}/imagen`, { method: 'PUT', datos: formulario })).data }
export async function eliminarImagenProducto(id: string, version: number): Promise<Producto> { return (await solicitarApi<RespuestaApi<Producto>>(`/productos/${id}/imagen`, { method: 'DELETE', datos: { version } })).data }
export async function inactivarProducto(id: string, version: number, motivo: string): Promise<void> { await solicitarApi(`/productos/${id}/inactivar`, { method: 'PATCH', datos: { version, motivo } }) }
export async function exportarProductos(datos: ExportarProductosParametros): Promise<void> { await descargarArchivoApi('/productos/exportaciones', { method: 'POST', datos, nombreArchivoAlternativo: `catalogo_medicamentos_${fechaArchivo()}.${datos.formato}` }) }
