import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { actualizarSucursal, obtenerSucursal } from '../sucursal-api'
import type { Sucursal } from '../sucursal.types'
import { validarFormularioSucursal, type DatosFormularioSucursal, type ErroresFormularioSucursal } from '../validacion-sucursal'
import { SucursalBreadcrumb } from './sucursal-breadcrumb'
import { SucursalFormularioCampos } from './sucursal-formulario-campos'
import styles from '../../roles/components/rol-formulario.module.css'

type Props = { sucursalId: string; onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }
const datosDesdeSucursal = (sucursal: Sucursal): DatosFormularioSucursal => ({ codigo: sucursal.codigo, nombre: sucursal.nombre, tipo: sucursal.tipo, direccion: sucursal.direccion, departamento: sucursal.departamento ?? '', municipio: sucursal.municipio ?? '', telefono: sucursal.telefono ?? '', correo: sucursal.correo ?? '' })
export function SucursalEditarView({ sucursalId, onNavegar, onCambiosPendientes }: Props) {
  const [sucursal, setSucursal] = useState<Sucursal | null>(null); const [datos, setDatos] = useState<DatosFormularioSucursal | null>(null); const [iniciales, setIniciales] = useState<DatosFormularioSucursal | null>(null); const [errores, setErrores] = useState<ErroresFormularioSucursal>({}); const [errorGeneral, setErrorGeneral] = useState<string | null>(null); const [guardando, setGuardando] = useState(false); const [exito, setExito] = useState(false); const [sinCambios, setSinCambios] = useState(false); const [revision, setRevision] = useState(0); const formularioRef = useRef<HTMLFormElement>(null)
  useEffect(() => { const controlador = new AbortController(); void obtenerSucursal(sucursalId, controlador.signal).then((respuesta) => { const valores = datosDesdeSucursal(respuesta); setSucursal(respuesta); setDatos(valores); setIniciales(valores); setErrorGeneral(null) }).catch((error: unknown) => { if (!controlador.signal.aborted) setErrorGeneral(error instanceof ErrorApi ? error.message : 'No fue posible cargar la sucursal.') }); return () => controlador.abort() }, [sucursalId, revision])
  const hayCambios = useMemo(() => Boolean(datos && iniciales && JSON.stringify(datos) !== JSON.stringify(iniciales)), [datos, iniciales]); useEffect(() => onCambiosPendientes(hayCambios && !exito), [exito, hayCambios, onCambiosPendientes]); useEffect(() => () => onCambiosPendientes(false), [onCambiosPendientes])
  const guardar = async (evento: FormEvent<HTMLFormElement>) => { evento.preventDefault(); if (!sucursal || !datos) return; const siguientes = validarFormularioSucursal(datos); setErrores(siguientes); if (Object.keys(siguientes).length) { formularioRef.current?.querySelector<HTMLElement>(`#${Object.keys(siguientes)[0]}`)?.focus(); return } if (!hayCambios) { setSinCambios(true); return } setGuardando(true); setErrorGeneral(null); try { const actualizado = await actualizarSucursal(sucursal.id, { version: sucursal.version, codigo: datos.codigo.trim().toUpperCase(), nombre: datos.nombre.trim(), tipo: datos.tipo as Exclude<typeof datos.tipo, ''>, direccion: datos.direccion.trim(), departamento: datos.departamento.trim() || null, municipio: datos.municipio.trim() || null, telefono: datos.telefono.trim() || null, correo: datos.correo.trim().toLowerCase() || null }); setSucursal(actualizado); onCambiosPendientes(false); setExito(true) } catch (error: unknown) { if (error instanceof ErrorApi) { setErrorGeneral(error.message); const erroresApi = Object.fromEntries(error.detalles.map((detalle) => [detalle.campo, detalle.mensaje])) as ErroresFormularioSucursal; if (Object.keys(erroresApi).length) setErrores(erroresApi) } else setErrorGeneral('No fue posible actualizar la sucursal.') } finally { setGuardando(false) } }
  if (!sucursal || !datos) return <section className={styles.estadoCargaFormulario}><SucursalBreadcrumb actual="Editar sucursal" onNavegar={onNavegar} /><h1>{errorGeneral ? 'No se pudo cargar la sucursal' : 'Cargando sucursal…'}</h1><p>{errorGeneral ?? 'Estamos preparando la información.'}</p>{errorGeneral && <button type="button" onClick={() => setRevision((valor) => valor + 1)}>Reintentar</button>}</section>
  return <section className={styles.paginaFormulario}><header className={styles.encabezadoPagina}><div><SucursalBreadcrumb actual="Editar sucursal" onNavegar={onNavegar} /><h1>Editar sucursal</h1></div><span className={styles.indicadorFormulario}>{sucursal.nombre}</span></header>{errorGeneral && <div className={styles.alertaError} role="alert"><span>!</span><p>{errorGeneral}</p></div>}<form ref={formularioRef} className={styles.formulario} onSubmit={(evento) => void guardar(evento)} noValidate><SucursalFormularioCampos datos={datos} errores={errores} deshabilitado={guardando} onChange={(siguientes) => { setDatos(siguientes); setErrores({}) }} /><div className={styles.accionesFormulario}><p><span aria-hidden="true">*</span> Campos obligatorios</p><div><button className={styles.botonSecundario} type="button" onClick={() => onNavegar('/organizacion/sucursales')} disabled={guardando}><IconoAccion nombre="cancelar" className={styles.iconoBoton} /><span>Cancelar</span></button><button className={styles.botonPrincipal} type="submit" disabled={guardando}><IconoAccion nombre="guardar" className={styles.iconoBoton} /><span>{guardando ? 'Guardando cambios…' : 'Guardar cambios'}</span></button></div></div></form><ModalEstado abierto={exito} tipo="exito" titulo="Sucursal actualizada" mensaje="La información fue actualizada correctamente." textoAccionPrincipal="Aceptar" onAccionPrincipal={() => onNavegar('/organizacion/sucursales')} onCerrar={() => onNavegar('/organizacion/sucursales')} /><ModalEstado abierto={sinCambios} tipo="informacion" titulo="Sin cambios por guardar" mensaje="No se editó ninguna información de la sucursal." textoAccionPrincipal="Aceptar" onAccionPrincipal={() => onNavegar('/organizacion/sucursales')} onCerrar={() => setSinCambios(false)} /></section>
}
