import { useEffect, useState } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { obtenerSucursal } from '../sucursal-api'
import type { Sucursal, TipoSucursal } from '../sucursal.types'
import { SucursalAuditoria } from './sucursal-auditoria'
import { SucursalBreadcrumb } from './sucursal-breadcrumb'
import { SucursalInactivarModal } from './sucursal-inactivar-modal'
import styles from '../../roles/components/rol-gestion.module.css'
type Props = { sucursalId: string; permisos: readonly string[]; onNavegar: (ruta: string) => void }
const etiquetasTipo: Record<TipoSucursal, string> = { FARMACIA: 'Farmacia', STAND: 'Stand', BODEGA: 'Bodega', OFICINA: 'Oficina' }
function fechaHora(valor: string | null): string { if (!valor) return 'Sin registro'; return new Intl.DateTimeFormat('es-GT', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Guatemala' }).format(new Date(valor)) }
export function SucursalDetalleView({ sucursalId, permisos, onNavegar }: Props) {
  const [sucursal, setSucursal] = useState<Sucursal | null>(null); const [error, setError] = useState<string | null>(null); const [revision, setRevision] = useState(0); const [confirmar, setConfirmar] = useState(false); const [exito, setExito] = useState(false)
  const puedeEditar = permisos.includes('ORGANIZACION.SUCURSALES.ACTUALIZAR'); const puedeInactivar = permisos.includes('ORGANIZACION.SUCURSALES.INACTIVAR'); const puedeVerAuditoria = permisos.includes('ORGANIZACION.SUCURSALES.VER_AUDITORIA')
  useEffect(() => { const controlador = new AbortController(); void obtenerSucursal(sucursalId, controlador.signal).then((respuesta) => { setSucursal(respuesta); setError(null) }).catch((errorActual: unknown) => { if (!controlador.signal.aborted) setError(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible cargar la sucursal.') }); return () => controlador.abort() }, [revision, sucursalId])
  if (!sucursal) return <section className={styles.errorPagina}><SucursalBreadcrumb actual="Detalle de la sucursal" onNavegar={onNavegar} /><h1>{error ? 'No se pudo cargar la sucursal' : 'Cargando sucursal…'}</h1><p>{error ?? 'Estamos consultando la información.'}</p>{error && <div><button type="button" onClick={() => setRevision((valor) => valor + 1)}>Reintentar</button><button type="button" onClick={() => onNavegar('/organizacion/sucursales')}>Ver listado</button></div>}</section>
  return <section className={styles.pagina}><SucursalBreadcrumb actual="Detalle de la sucursal" onNavegar={onNavegar} /><header className={styles.cabeceraDetalle}><div className={styles.perfilRol}><span className={styles.iconoRol} aria-hidden="true">{sucursal.nombre.trim().slice(0, 2).toUpperCase()}</span><div><p>Sucursal {sucursal.codigo}</p><h1>{sucursal.nombre}</h1><span className={`${styles.estado} ${sucursal.activo ? styles.activo : styles.inactivo}`}>{sucursal.activo ? 'Activa' : 'Inactiva'}</span></div></div><div className={styles.accionesCabecera}>{puedeEditar && <button className={styles.botonEditar} type="button" onClick={() => onNavegar(`/organizacion/sucursales/${sucursal.id}/editar`)}><IconoAccion nombre="editar" /><span>Editar información</span></button>}{puedeInactivar && sucursal.activo && <button className={styles.botonPeligro} type="button" onClick={() => setConfirmar(true)}><IconoAccion nombre="desactivar" /><span>Desactivar sucursal</span></button>}</div></header><div className={styles.grillaDetalle}><article className={styles.tarjetaDetalle}><h2>Información general</h2><dl><div><dt>Código</dt><dd>{sucursal.codigo}</dd></div><div><dt>Tipo</dt><dd>{etiquetasTipo[sucursal.tipo]}</dd></div><div><dt>Situación</dt><dd>{sucursal.activo ? 'Activa' : 'Inactiva'}</dd></div><div className={styles.datoCompleto}><dt>Dirección</dt><dd>{sucursal.direccion}</dd></div>{!sucursal.activo && <div className={styles.datoCompleto}><dt>Motivo de desactivación</dt><dd>{sucursal.motivoInactivacion ?? 'Sin motivo registrado'}</dd></div>}</dl></article><article className={styles.tarjetaDetalle}><h2>Ubicación y contacto</h2><dl><div><dt>Departamento</dt><dd>{sucursal.departamento ?? 'Sin registro'}</dd></div><div><dt>Municipio</dt><dd>{sucursal.municipio ?? 'Sin registro'}</dd></div><div><dt>Teléfono</dt><dd>{sucursal.telefono ?? 'Sin registro'}</dd></div><div><dt>Correo</dt><dd>{sucursal.correo ?? 'Sin registro'}</dd></div></dl></article><article className={styles.tarjetaDetalle}><h2>Control del registro</h2><dl><div><dt>Creada</dt><dd>{fechaHora(sucursal.creadoEn)}</dd></div><div><dt>Última actualización</dt><dd>{fechaHora(sucursal.actualizadoEn)}</dd></div><div><dt>Desactivada</dt><dd>{fechaHora(sucursal.inactivadoEn)}</dd></div><div><dt>Versión</dt><dd>{sucursal.version}</dd></div></dl></article></div>{puedeVerAuditoria && <SucursalAuditoria sucursalId={sucursal.id} revision={sucursal.version} />}<SucursalInactivarModal sucursal={confirmar ? sucursal : null} onCerrar={() => setConfirmar(false)} onInactivada={() => { setConfirmar(false); setExito(true) }} /><ModalEstado abierto={exito} tipo="exito" titulo="Sucursal desactivada" mensaje={`La sucursal ${sucursal.nombre} fue desactivada correctamente.`} textoAccionPrincipal="Aceptar" onAccionPrincipal={() => onNavegar('/organizacion/sucursales')} onCerrar={() => onNavegar('/organizacion/sucursales')} /></section>
}
