import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { crearSucursal } from '../sucursal-api'
import { validarFormularioSucursal, type DatosFormularioSucursal, type ErroresFormularioSucursal } from '../validacion-sucursal'
import { SucursalBreadcrumb } from './sucursal-breadcrumb'
import { SucursalFormularioCampos } from './sucursal-formulario-campos'
import styles from '../../roles/components/rol-formulario.module.css'

type Props = { onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }
const iniciales: DatosFormularioSucursal = { codigo: '', nombre: '', tipo: '', direccion: '', departamento: '', municipio: '', telefono: '', correo: '' }
export function SucursalCrearView({ onNavegar, onCambiosPendientes }: Props) {
  const [datos, setDatos] = useState(iniciales); const [errores, setErrores] = useState<ErroresFormularioSucursal>({}); const [errorGeneral, setErrorGeneral] = useState<string | null>(null); const [guardando, setGuardando] = useState(false); const [exito, setExito] = useState(false); const formularioRef = useRef<HTMLFormElement>(null)
  const tieneCambios = useMemo(() => JSON.stringify(datos) !== JSON.stringify(iniciales), [datos])
  useEffect(() => onCambiosPendientes(tieneCambios && !exito), [exito, onCambiosPendientes, tieneCambios]); useEffect(() => () => onCambiosPendientes(false), [onCambiosPendientes])
  const guardar = async (evento: FormEvent<HTMLFormElement>) => { evento.preventDefault(); const siguientes = validarFormularioSucursal(datos); setErrores(siguientes); if (Object.keys(siguientes).length) { formularioRef.current?.querySelector<HTMLElement>(`#${Object.keys(siguientes)[0]}`)?.focus(); return } setGuardando(true); setErrorGeneral(null); try { await crearSucursal({ codigo: datos.codigo.trim().toUpperCase(), nombre: datos.nombre.trim(), tipo: datos.tipo as Exclude<typeof datos.tipo, ''>, direccion: datos.direccion.trim(), departamento: datos.departamento.trim() || null, municipio: datos.municipio.trim() || null, telefono: datos.telefono.trim() || null, correo: datos.correo.trim().toLowerCase() || null }); onCambiosPendientes(false); setExito(true) } catch (error: unknown) { if (error instanceof ErrorApi) { setErrorGeneral(error.message); const erroresApi = Object.fromEntries(error.detalles.map((detalle) => [detalle.campo, detalle.mensaje])) as ErroresFormularioSucursal; if (Object.keys(erroresApi).length) setErrores(erroresApi) } else setErrorGeneral('No fue posible registrar la sucursal.') } finally { setGuardando(false) } }
  return <section className={styles.paginaFormulario}><header className={styles.encabezadoPagina}><div><SucursalBreadcrumb actual="Crear sucursal" onNavegar={onNavegar} /><h1>Crear sucursal</h1></div></header>{errorGeneral && <div className={styles.alertaError} role="alert"><span>!</span><p>{errorGeneral}</p></div>}<form ref={formularioRef} className={styles.formulario} onSubmit={(evento) => void guardar(evento)} noValidate><SucursalFormularioCampos datos={datos} errores={errores} deshabilitado={guardando} onChange={(siguientes) => { setDatos(siguientes); setErrores({}) }} /><div className={styles.accionesFormulario}><p><span aria-hidden="true">*</span> Campos obligatorios</p><div><button className={styles.botonSecundario} type="button" onClick={() => onNavegar('/organizacion/sucursales')} disabled={guardando}><IconoAccion nombre="cancelar" className={styles.iconoBoton} /><span>Cancelar</span></button><button className={styles.botonPrincipal} type="submit" disabled={guardando}><IconoAccion nombre="guardar" className={styles.iconoBoton} /><span>{guardando ? 'Registrando sucursal…' : 'Registrar sucursal'}</span></button></div></div></form><ModalEstado abierto={exito} tipo="exito" titulo="Sucursal registrada" mensaje="La sucursal fue guardada correctamente." textoAccionPrincipal="Aceptar" onAccionPrincipal={() => onNavegar('/organizacion/sucursales')} onCerrar={() => onNavegar('/organizacion/sucursales')} /></section>
}
