import { useEffect, useMemo, useState } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { PaginacionTabla, TablaDatos, type ColumnaTabla, type ColumnFiltersState, type SortingState } from '../../../shared/components/tabla-datos'
import { listarAuditoriaSucursal } from '../sucursal-api'
import type { AuditoriaSucursalPaginada, EventoAuditoriaSucursal, ListarAuditoriaSucursalParametros, OperacionAuditoriaSucursal, OrdenAuditoriaSucursal } from '../sucursal.types'
import styles from '../../roles/components/rol-gestion.module.css'
type Props = { sucursalId: string; revision: number }
const valorTexto = (filtros: ColumnFiltersState, id: string) => { const valor = filtros.find((filtro) => filtro.id === id)?.value; return typeof valor === 'string' && valor.trim() ? valor.trim() : undefined }
const valores = (filtros: ColumnFiltersState, id: string) => { const valor = filtros.find((filtro) => filtro.id === id)?.value; return Array.isArray(valor) && valor.length ? valor.map(String) : undefined }
const fechaHora = (valor: string) => new Intl.DateTimeFormat('es-GT', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Guatemala' }).format(new Date(valor))
const etiquetaOperacion: Record<OperacionAuditoriaSucursal, string> = { CREAR: 'Creación', ACTUALIZAR: 'Actualización', INACTIVAR: 'Desactivación' }
function valorAuditoria(valor: string | null): string { if (valor === null || valor === '') return 'Sin valor'; if (valor === 'true') return 'Sí'; if (valor === 'false') return 'No'; return valor }
function DetalleCambios({ evento }: { evento: EventoAuditoriaSucursal }) { return <div id={`detalle-auditoria-sucursal-${evento.id}`} className={styles.detalleAuditoria}><h3>Cambios registrados</h3><div className={styles.tablaCambiosContenedor}><table><thead><tr><th>Campo</th><th>Valor anterior</th><th>Valor nuevo</th></tr></thead><tbody>{evento.detalles.map((detalle) => <tr key={detalle.id}><th scope="row">{detalle.etiquetaPropiedad ?? detalle.nombrePropiedad}</th><td>{valorAuditoria(detalle.valorAnterior)}</td><td>{valorAuditoria(detalle.valorNuevo)}</td></tr>)}</tbody></table></div></div> }
export function SucursalAuditoria({ sucursalId, revision }: Props) {
  const [resultado, setResultado] = useState<AuditoriaSucursalPaginada | null>(null); const [pagina, setPagina] = useState(1); const [tamanoPagina, setTamanoPagina] = useState(50); const [filtros, setFiltros] = useState<ColumnFiltersState>([]); const [ordenamiento, setOrdenamiento] = useState<SortingState>([{ id: 'fecha', desc: true }]); const [error, setError] = useState<string | null>(null); const [solicitudFinalizada, setSolicitudFinalizada] = useState(''); const [reintento, setReintento] = useState(0); const [expandido, setExpandido] = useState<string | null>(null)
  const parametros = useMemo<ListarAuditoriaSucursalParametros>(() => { const orden = ordenamiento[0]; return { pagina, tamanoPagina, fecha: valorTexto(filtros, 'fecha'), operaciones: valores(filtros, 'operacion') as OperacionAuditoriaSucursal[] | undefined, usuario: valorTexto(filtros, 'usuario'), sucursal: valorTexto(filtros, 'sucursal'), resumen: valorTexto(filtros, 'resumen'), orden: (orden?.id ?? 'fecha') as OrdenAuditoriaSucursal, direccion: orden?.desc === false ? 'asc' : 'desc' } }, [filtros, ordenamiento, pagina, tamanoPagina])
  const clave = useMemo(() => JSON.stringify({ sucursalId, parametros, revision, reintento }), [parametros, reintento, revision, sucursalId]); const cargando = solicitudFinalizada !== clave
  useEffect(() => { const controlador = new AbortController(); void listarAuditoriaSucursal(sucursalId, parametros, controlador.signal).then((respuesta) => { setResultado(respuesta); setExpandido(null); setError(null) }).catch((errorActual: unknown) => { if (!controlador.signal.aborted) setError(errorActual instanceof ErrorApi ? errorActual.message : 'No fue posible cargar la pista de auditoría.') }).finally(() => { if (!controlador.signal.aborted) setSolicitudFinalizada(clave) }); return () => controlador.abort() }, [clave, parametros, sucursalId])
  const columnas = useMemo<ColumnaTabla<EventoAuditoriaSucursal>[]>(() => [
    { id: 'fecha', titulo: 'Fecha y hora', obtenerValor: (evento) => evento.ocurridoEn, ordenable: true, filtro: { tipo: 'fecha', etiqueta: 'Filtrar por fecha' }, celda: (evento) => fechaHora(evento.ocurridoEn) },
    { id: 'operacion', titulo: 'Operación', obtenerValor: (evento) => evento.tipoOperacion, ordenable: true, filtro: { tipo: 'opciones', etiqueta: 'Seleccionar operación', buscable: false, opciones: Object.entries(etiquetaOperacion).map(([valor, etiqueta]) => ({ valor, etiqueta })) }, celda: (evento) => <span className={styles.etiquetaOperacion}>{etiquetaOperacion[evento.tipoOperacion]}</span> },
    { id: 'usuario', titulo: 'Usuario', obtenerValor: (evento) => evento.usuarioNombre ?? '', ordenable: true, filtro: { tipo: 'texto', etiqueta: 'Filtrar usuario', placeholder: 'Nombre de usuario' }, celda: (evento) => evento.usuarioNombre ?? <span className={styles.sinDato}>Sistema</span> },
    { id: 'sucursal', titulo: 'Sucursal de sesión', obtenerValor: (evento) => evento.sucursal?.nombre ?? '', ordenable: true, filtro: { tipo: 'texto', etiqueta: 'Filtrar sucursal', placeholder: 'Sucursal' }, celda: (evento) => evento.sucursal ? <span>{evento.sucursal.nombre}<small className={styles.codigoSecundario}>{evento.sucursal.codigo}</small></span> : <span className={styles.sinDato}>Sin sucursal</span> },
    { id: 'resumen', titulo: 'Resumen', obtenerValor: (evento) => evento.resumen ?? '', ordenable: true, filtro: { tipo: 'texto', etiqueta: 'Filtrar resumen', placeholder: 'Descripción del evento' }, celda: (evento) => evento.resumen ?? <span className={styles.sinDato}>Sin resumen</span> },
    { id: 'cambios', titulo: 'Cambios', obtenerValor: (evento) => evento.detalles.length, celda: (evento) => evento.detalles.length ? <button className={styles.botonCambiosAuditoria} type="button" aria-expanded={expandido === evento.id} aria-controls={`detalle-auditoria-sucursal-${evento.id}`} onClick={() => setExpandido((actual) => actual === evento.id ? null : evento.id)}>{expandido === evento.id ? 'Ocultar' : `Ver (${evento.detalles.length})`}</button> : <span className={styles.sinDato}>Sin detalle</span> },
  ], [expandido])
  return <article className={styles.tarjetaDetalle} aria-busy={cargando}><div className={styles.tituloHistorial}><div><h2>Pista de auditoría</h2><p>Consulta quién creó, modificó o desactivó esta sucursal.</p></div><div className={styles.accionesResumen}>{cargando && <span role="status">Actualizando…</span>}{resultado && <span>{resultado.total} {resultado.total === 1 ? 'evento' : 'eventos'}</span>}{filtros.length > 0 && <button type="button" onClick={() => { setFiltros([]); setPagina(1) }}>Limpiar filtros ({filtros.length})</button>}</div></div>{error && <div className={styles.errorAuditoria} role="alert"><span>{error}</span><button type="button" onClick={() => setReintento((valor) => valor + 1)}>Reintentar</button></div>}{!resultado && cargando ? <p className={styles.sinHistorial}>Cargando pista de auditoría…</p> : resultado?.items.length ? <div className={styles.tablaTanstackAuditoria}><TablaDatos descripcion="Pista de auditoría de la sucursal" datos={resultado.items} columnas={columnas} filtros={filtros} ordenamiento={ordenamiento} obtenerIdFila={(evento) => evento.id} onFiltrosChange={(siguientes) => { setFiltros(siguientes); setPagina(1) }} onOrdenamientoChange={(siguiente) => { setOrdenamiento(siguiente.length ? siguiente : [{ id: 'fecha', desc: true }]); setPagina(1) }} renderizarFilaExpandida={(evento) => evento.id === expandido ? <DetalleCambios evento={evento} /> : null} /><PaginacionTabla pagina={resultado.pagina} tamanoPagina={resultado.tamanoPagina} total={resultado.total} totalPaginas={resultado.totalPaginas} unidadSingular="evento" unidadPlural="eventos" onPaginaChange={setPagina} onTamanoPaginaChange={(tamano) => { setTamanoPagina(tamano); setPagina(1) }} /></div> : !error ? <p className={styles.sinHistorial}>{filtros.length ? 'No hay eventos que coincidan con los filtros.' : 'No hay eventos de auditoría registrados para esta sucursal.'}</p> : null}</article>
}
