import { useState } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import type { crearCatalogoMaestroApi } from '../catalogo-maestro-api'
import type { CatalogoMaestroRegistro, ConfiguracionCatalogo } from '../catalogo-maestro.types'
import styles from '../../roles/components/rol-gestion.module.css'
type Api = ReturnType<typeof crearCatalogoMaestroApi>
export function CatalogoInactivarModal({ config, api, item, onCerrar, onInactivado }: { config: ConfiguracionCatalogo; api: Api; item: CatalogoMaestroRegistro | null; onCerrar: () => void; onInactivado: () => void }) { const [motivo, setMotivo] = useState(''); const [error, setError] = useState<string | null>(null); const [procesando, setProcesando] = useState(false); const cerrar = () => { if (!procesando) { setMotivo(''); setError(null); onCerrar() } }; const confirmar = async () => { if (!item) return; if (motivo.trim().length < 5) { setError('Escribe un motivo de al menos 5 caracteres.'); return } setProcesando(true); try { await api.inactivar(item.id, item.version, motivo.trim()); setMotivo(''); onInactivado() } catch (e: unknown) { setError(e instanceof ErrorApi ? e.message : `No fue posible desactivar ${config.singular.toLowerCase()}.`) } finally { setProcesando(false) } }; return <ModalEstado abierto={Boolean(item)} tipo="advertencia" titulo={`Desactivar ${config.singular.toLowerCase()}`} mensaje={item ? <div className={styles.contenidoConfirmacion}><p><strong>{item.nombre}</strong> dejará de estar disponible para nuevos registros.</p><label htmlFor={`motivo-${config.recurso}`}>Motivo de desactivación</label><textarea id={`motivo-${config.recurso}`} rows={3} maxLength={250} value={motivo} onChange={(e) => { setMotivo(e.target.value); setError(null) }} /><small>{motivo.length}/250 caracteres</small>{error && <span role="alert">{error}</span>}</div> : ''} textoAccionPrincipal={`Desactivar ${config.singular.toLowerCase()}`} iconoAccionPrincipal={<IconoAccion nombre="desactivar" />} textoAccionSecundaria="Cancelar" iconoAccionSecundaria={<IconoAccion nombre="cancelar" />} varianteAccionPrincipal="peligro" onAccionPrincipal={() => void confirmar()} onAccionSecundaria={cerrar} onCerrar={cerrar} cargando={procesando} /> }
