import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { SelectorCatalogoBuscable } from '../../../shared/components/selector-catalogo-buscable'
import { crearRegistroAbastecimiento, listarRecepcionesElegiblesDevolucion, listarUbicacionesAbastecimiento, obtenerOpcionesAbastecimiento } from '../abastecimiento-api'
import type { CrearDevolucionProveedorRequest, DevolucionProveedor, OpcionesFiltrosAbastecimiento, RecepcionElegibleDevolucion, UbicacionAbastecimiento } from '../abastecimiento.types'
import { AbastecimientoBreadcrumb } from './abastecimiento-breadcrumb'
import styles from './abastecimiento.module.css'

export function DevolucionCrearView({ sucursalActualId, onNavegar, onCambiosPendientes }: { sucursalActualId: string; onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }) {
  const [opciones, setOpciones] = useState<OpcionesFiltrosAbastecimiento | null>(null); const [ubicaciones, setUbicaciones] = useState<UbicacionAbastecimiento[]>([]); const [elegibles, setElegibles] = useState<RecepcionElegibleDevolucion[]>([])
  const [proveedorId, setProveedorId] = useState(''); const [ubicacionId, setUbicacionId] = useState(''); const [motivo, setMotivo] = useState(''); const [evidencia, setEvidencia] = useState(''); const [busqueda, setBusqueda] = useState('')
  const [seleccion, setSeleccion] = useState<Record<string, boolean>>({}); const [cantidades, setCantidades] = useState<Record<string, string>>({}); const [causas, setCausas] = useState<Record<string, string>>({}); const [errores, setErrores] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null); const [cargando, setCargando] = useState(false); const [guardando, setGuardando] = useState(false); const [guardada, setGuardada] = useState<DevolucionProveedor | null>(null)
  useEffect(() => { const c = new AbortController(); void Promise.all([obtenerOpcionesAbastecimiento(c.signal), listarUbicacionesAbastecimiento(sucursalActualId, c.signal)]).then(([o, u]) => { setOpciones(o); setUbicaciones(u) }).catch((e: unknown) => { if (!c.signal.aborted) setError(e instanceof ErrorApi ? e.message : 'No fue posible cargar los catálogos.') }); return () => c.abort() }, [sucursalActualId])
  useEffect(() => { if (!proveedorId || !ubicacionId) return; const c = new AbortController(); const t = window.setTimeout(() => { setCargando(true); void listarRecepcionesElegiblesDevolucion({ proveedorId, ubicacionId, busqueda: busqueda.trim() || undefined, limite: 100 }, c.signal).then((r) => { setElegibles(r); setError(null) }).catch((e: unknown) => { if (!c.signal.aborted) setError(e instanceof ErrorApi ? e.message : 'No fue posible cargar las recepciones elegibles.') }).finally(() => { if (!c.signal.aborted) setCargando(false) }) }, 250); return () => { window.clearTimeout(t); c.abort() } }, [busqueda, proveedorId, ubicacionId])
  const seleccionadas = useMemo(() => elegibles.filter((x) => seleccion[x.recepcionDetalleId]), [elegibles, seleccion]); const tieneCambios = Boolean(proveedorId || ubicacionId || motivo || evidencia || seleccionadas.length)
  useEffect(() => onCambiosPendientes(!guardada && tieneCambios), [guardada, onCambiosPendientes, tieneCambios]); useEffect(() => () => onCambiosPendientes(false), [onCambiosPendientes])
  const enviar = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const x: Record<string, string> = {}; if (!proveedorId) x.proveedorId = 'Selecciona el proveedor.'; if (!ubicacionId) x.ubicacionId = 'Selecciona la ubicación.'; if (motivo.trim().length < 10 || motivo.trim().length > 1000) x.motivo = 'El motivo debe contener de 10 a 1000 caracteres.'; if (evidencia.trim().length > 500) x.evidencia = 'La evidencia admite máximo 500 caracteres.'; if (!seleccionadas.length) x.detalles = 'Selecciona al menos una recepción elegible.'; if (seleccionadas.some((d) => !(Number(cantidades[d.recepcionDetalleId]) > 0) || Number(cantidades[d.recepcionDetalleId]) > Number(d.cantidadElegible))) x.detalles = 'Cada cantidad debe ser mayor que cero y no exceder lo elegible.'; if (seleccionadas.some((d) => (causas[d.recepcionDetalleId] ?? '').trim().length < 5)) x.detalles = 'Documenta una causa de al menos 5 caracteres por producto.'; setErrores(x); if (Object.keys(x).length) return
    const datos: CrearDevolucionProveedorRequest = { proveedorId, ubicacionId, motivo: motivo.trim(), evidenciaReferencia: evidencia.trim() || null, detalles: seleccionadas.map((d) => ({ recepcionDetalleId: d.recepcionDetalleId, productoId: d.producto.id, loteId: d.lote?.id ?? null, cantidad: Number(cantidades[d.recepcionDetalleId]), causa: causas[d.recepcionDetalleId]!.trim() })) }
    setGuardando(true); setError(null); try { setGuardada(await crearRegistroAbastecimiento<DevolucionProveedor>('devoluciones', datos)); onCambiosPendientes(false) } catch (err) { setError(err instanceof ErrorApi ? err.message : 'No fue posible solicitar la devolución.') } finally { setGuardando(false) }
  }
  return <><section className={styles.pagina} aria-labelledby="titulo-nueva-devolucion"><AbastecimientoBreadcrumb recurso="devoluciones" actual="Nueva devolución" onNavegar={onNavegar} /><header className={styles.encabezadoPagina}><div><p className={styles.sobretitulo}>Devolución a proveedor</p><h1 id="titulo-nueva-devolucion">Solicitar devolución</h1><p>Solo se muestran cantidades aceptadas en recepciones técnicamente conformes que aún no han sido devueltas.</p></div></header>{error && <div className={styles.alertaError} role="alert">{error}</div>}<form className={styles.formulario} onSubmit={enviar}><fieldset disabled={guardando}><legend>Proveedor y ubicación</legend><div className={styles.grillaDos}><div className={styles.campo}><label htmlFor="devolucion-proveedorId">Proveedor <span>*</span></label><SelectorCatalogoBuscable id="devolucion-proveedorId" valor={proveedorId} opciones={(opciones?.proveedores ?? []).map((x) => ({ valor: x.id, etiqueta: `${x.codigo} — ${x.nombre}` }))} placeholder="Selecciona el proveedor" invalido={Boolean(errores.proveedorId)} onChange={(v) => { setProveedorId(v); setSeleccion({}) }} />{errores.proveedorId && <small className={styles.errorCampo}>{errores.proveedorId}</small>}</div><div className={styles.campo}><label htmlFor="devolucion-ubicacionId">Ubicación de salida <span>*</span></label><select id="devolucion-ubicacionId" value={ubicacionId} aria-invalid={Boolean(errores.ubicacionId)} onChange={(e) => setUbicacionId(e.target.value)}><option value="">Selecciona una ubicación</option>{ubicaciones.filter((x) => x.activa !== false && !x.bloqueada).map((x) => <option key={x.id} value={x.id}>{x.codigo} — {x.nombre}</option>)}</select>{errores.ubicacionId && <small className={styles.errorCampo}>{errores.ubicacionId}</small>}</div></div></fieldset>
  <fieldset disabled={guardando || !proveedorId || !ubicacionId}><legend>Recepciones elegibles</legend><div className={styles.campo}><label htmlFor="devolucion-busqueda">Buscar producto, lote o recepción</label><input id="devolucion-busqueda" type="search" value={busqueda} onChange={(e) => setBusqueda(e.target.value)} /></div>{cargando ? <div className={styles.estadoVacioCompacto}><h3>Cargando recepciones…</h3></div> : !elegibles.length ? <div className={styles.estadoVacioCompacto}><h3>Sin cantidades elegibles</h3><p>Selecciona otro proveedor o ubicación, o verifica que exista una recepción técnica conforme.</p></div> : <div className={styles.lineasRecepcion}>{elegibles.map((d) => <article className={`${styles.lineaRecepcion} ${seleccion[d.recepcionDetalleId] ? '' : styles.lineaCotizacionExcluida}`} key={d.recepcionDetalleId}><label className={styles.incluirCotizacion}><input type="checkbox" checked={Boolean(seleccion[d.recepcionDetalleId])} onChange={(e) => { const activo = e.target.checked; setSeleccion((a) => ({ ...a, [d.recepcionDetalleId]: activo })); if (activo) setCantidades((a) => ({ ...a, [d.recepcionDetalleId]: String(d.cantidadElegible) })) }} /><span><strong>{d.producto.codigo} — {d.producto.nombre}</strong><small>Recepción {d.recepcionNumero} · lote {d.lote?.numeroLote ?? 'sin lote'} · elegible {d.cantidadElegible}</small></span></label>{seleccion[d.recepcionDetalleId] && <div className={styles.grillaDos}><div className={styles.campo}><label>Cantidad a devolver <span>*</span></label><input type="number" min="0.000001" max={d.cantidadElegible} step="0.000001" value={cantidades[d.recepcionDetalleId] ?? ''} onChange={(e) => setCantidades((a) => ({ ...a, [d.recepcionDetalleId]: e.target.value }))} /></div><div className={styles.campo}><label>Causa <span>*</span></label><input maxLength={500} value={causas[d.recepcionDetalleId] ?? ''} onChange={(e) => setCausas((a) => ({ ...a, [d.recepcionDetalleId]: e.target.value }))} /></div></div>}</article>)}</div>}{errores.detalles && <small className={styles.errorCampo}>{errores.detalles}</small>}</fieldset>
  <fieldset disabled={guardando}><legend>Motivo y evidencia</legend><div className={styles.campo}><label htmlFor="devolucion-motivo">Motivo general <span>*</span></label><textarea id="devolucion-motivo" rows={5} maxLength={1000} value={motivo} aria-invalid={Boolean(errores.motivo)} onChange={(e) => setMotivo(e.target.value)} />{errores.motivo && <small className={styles.errorCampo}>{errores.motivo}</small>}</div><div className={styles.campo}><label htmlFor="devolucion-evidencia">Referencia de evidencia</label><input id="devolucion-evidencia" maxLength={500} value={evidencia} onChange={(e) => setEvidencia(e.target.value)} />{errores.evidencia && <small className={styles.errorCampo}>{errores.evidencia}</small>}</div></fieldset><div className={styles.accionesFormulario}><p>* Campos obligatorios</p><div><button className={styles.botonNeutral} type="button" onClick={() => onNavegar('/abastecimiento/devoluciones')}><IconoAccion nombre="cancelar" />Volver sin guardar</button><button className={styles.botonPrimario} type="submit" disabled={guardando}><IconoAccion nombre="guardar" />{guardando ? 'Guardando…' : 'Solicitar devolución'}</button></div></div></form></section><ModalEstado abierto={Boolean(guardada)} tipo="exito" titulo="Devolución solicitada" mensaje={guardada ? `La devolución ${guardada.numero} quedó pendiente de aprobación interna.` : ''} textoAccionPrincipal="Ver devolución" onAccionPrincipal={() => onNavegar(`/abastecimiento/devoluciones/${guardada?.id}`)} onCerrar={() => onNavegar(`/abastecimiento/devoluciones/${guardada?.id}`)} /></>
}
