import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { ejecutarAccionAbastecimiento, obtenerRegistroAbastecimiento } from '../abastecimiento-api'
import { etiquetaCodigo } from '../abastecimiento-config'
import type { DevolucionProveedor } from '../abastecimiento.types'
import { AbastecimientoBreadcrumb } from './abastecimiento-breadcrumb'
import styles from './abastecimiento.module.css'

type Modo = 'autorizar' | 'segregar' | 'despachar' | 'recibir' | 'compensar' | 'cerrar' | 'cancelar'
const n = (v: unknown) => Number(v ?? 0)
const titulos: Record<Modo, string> = { autorizar: 'Autorizar devolución', segregar: 'Segregar productos', despachar: 'Despachar devolución', recibir: 'Registrar recepción del proveedor', compensar: 'Registrar compensación', cerrar: 'Cerrar devolución', cancelar: 'Cancelar devolución' }

export function DevolucionAccionView({ devolucionId, modo, onNavegar, onCambiosPendientes }: { devolucionId: string; modo: Modo; onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }) {
  const [devolucion, setDevolucion] = useState<DevolucionProveedor | null>(null); const [error, setError] = useState<string | null>(null); const [guardando, setGuardando] = useState(false); const [guardada, setGuardada] = useState<DevolucionProveedor | null>(null); const [aprobar, setAprobar] = useState(true); const [motivo, setMotivo] = useState(''); const [autorizacion, setAutorizacion] = useState(''); const [referencia, setReferencia] = useState(''); const [evidencia, setEvidencia] = useState(''); const [cantidades, setCantidades] = useState<Record<string, string>>({}); const [rechazadas, setRechazadas] = useState<Record<string, string>>({}); const [errores, setErrores] = useState<Record<string, string>>({})
  useEffect(() => { const c = new AbortController(); void obtenerRegistroAbastecimiento<DevolucionProveedor>('devoluciones', devolucionId, c.signal).then((r) => { setDevolucion(r); setCantidades(Object.fromEntries(r.detalles.map((d) => [d.id, String(r.estado === 'APROBACION_INTERNA' ? n(d.cantidad) : n(d.cantidadAutorizada))]))); setRechazadas(Object.fromEntries(r.detalles.map((d) => [d.id, '0']))) }).catch((e: unknown) => { if (!c.signal.aborted) setError(e instanceof ErrorApi ? e.message : 'No fue posible cargar la devolución.') }); return () => c.abort() }, [devolucionId])
  const disponible = useMemo(() => devolucion && (modo === 'autorizar' ? ['SOLICITADA', 'APROBACION_INTERNA'].includes(devolucion.estado) : modo === 'segregar' ? devolucion.estado === 'AUTORIZADA_PROVEEDOR' : modo === 'despachar' ? devolucion.estado === 'SEGREGADA' : modo === 'recibir' ? devolucion.estado === 'DESPACHADA' : modo === 'compensar' ? devolucion.estado === 'RECIBIDA_PROVEEDOR' : modo === 'cerrar' ? devolucion.estado === 'COMPENSADA' : ['SOLICITADA', 'APROBACION_INTERNA', 'AUTORIZADA_PROVEEDOR', 'SEGREGADA'].includes(devolucion.estado)), [devolucion, modo])
  const tieneCambios = Boolean(motivo || autorizacion || referencia || evidencia || !aprobar || Object.values(rechazadas).some((x) => n(x) > 0)); useEffect(() => onCambiosPendientes(!guardada && tieneCambios), [guardada, onCambiosPendientes, tieneCambios]); useEffect(() => () => onCambiosPendientes(false), [onCambiosPendientes])
  const enviar = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); if (!devolucion || !disponible) return; const x: Record<string, string> = {}; const faseProveedor = modo === 'autorizar' && devolucion.estado === 'APROBACION_INTERNA'
    if (['autorizar', 'recibir', 'compensar', 'cerrar', 'cancelar'].includes(modo) && (motivo.trim().length < 5 || motivo.trim().length > 500)) x.motivo = 'El motivo debe contener de 5 a 500 caracteres.'
    if (faseProveedor && aprobar && (autorizacion.trim().length < 1 || autorizacion.trim().length > 200)) x.autorizacion = 'Ingresa la autorización del proveedor, con máximo 200 caracteres.'
    if (faseProveedor && aprobar && devolucion.detalles.every((d) => n(cantidades[d.id]) <= 0)) x.detalles = 'Autoriza al menos una cantidad mayor que cero.'
    if (faseProveedor && aprobar && devolucion.detalles.some((d) => n(cantidades[d.id]) < 0 || n(cantidades[d.id]) > n(d.cantidad))) x.detalles = 'La cantidad autorizada no puede exceder lo solicitado.'
    if (modo === 'recibir') { if (evidencia.trim().length < 3 || evidencia.trim().length > 500) x.evidencia = 'La evidencia debe contener de 3 a 500 caracteres.'; if (devolucion.detalles.some((d) => n(cantidades[d.id]) + n(rechazadas[d.id]) !== n(d.cantidadAutorizada))) x.detalles = 'Aceptado más rechazado debe coincidir con la cantidad autorizada.' }
    if (modo === 'compensar' && (referencia.trim().length < 3 || referencia.trim().length > 200)) x.referencia = 'La referencia debe contener de 3 a 200 caracteres.'
    setErrores(x); if (Object.keys(x).length) return
    let accion = ''; let datos: unknown
    if (modo === 'autorizar') { accion = 'autorizacion'; datos = { version: devolucion.version, aprobar, motivo: motivo.trim(), autorizacionProveedor: faseProveedor && aprobar ? autorizacion.trim() : undefined, detalles: faseProveedor && aprobar ? devolucion.detalles.map((d) => ({ detalleId: d.id, cantidadAutorizada: n(cantidades[d.id]) })) : undefined } }
    else if (modo === 'segregar' || modo === 'despachar') { accion = modo === 'segregar' ? 'segregacion' : 'despacho'; datos = { version: devolucion.version } }
    else if (modo === 'recibir') { accion = 'recepcion-proveedor'; datos = { version: devolucion.version, motivo: motivo.trim(), evidenciaReferencia: evidencia.trim(), detalles: devolucion.detalles.map((d) => ({ detalleId: d.id, cantidadAceptada: n(cantidades[d.id]), cantidadRechazada: n(rechazadas[d.id]) })) } }
    else if (modo === 'compensar') { accion = 'compensacion'; datos = { version: devolucion.version, referencia: referencia.trim(), motivo: motivo.trim() } }
    else { accion = modo === 'cerrar' ? 'cierre' : 'cancelacion'; datos = { version: devolucion.version, motivo: motivo.trim() } }
    setGuardando(true); setError(null); try { setGuardada(await ejecutarAccionAbastecimiento<DevolucionProveedor>('devoluciones', devolucion.id, accion, datos)); onCambiosPendientes(false) } catch (err) { setError(err instanceof ErrorApi ? err.message : 'No fue posible completar la acción.') } finally { setGuardando(false) }
  }
  if (!devolucion && !error) return <section className={styles.pagina} aria-busy="true"><AbastecimientoBreadcrumb recurso="devoluciones" actual={titulos[modo]} onNavegar={onNavegar} /><div className={styles.estadoVacio}><h1>Cargando devolución</h1></div></section>
  const faseProveedor = devolucion?.estado === 'APROBACION_INTERNA'
  return <><section className={styles.pagina} aria-labelledby="titulo-accion-devolucion"><AbastecimientoBreadcrumb recurso="devoluciones" actual={titulos[modo]} onNavegar={onNavegar} /><header className={styles.encabezadoPagina}><div><p className={styles.sobretitulo}>Devolución {devolucion?.numero ?? ''}</p><h1 id="titulo-accion-devolucion">{modo === 'autorizar' && faseProveedor ? 'Registrar autorización del proveedor' : titulos[modo]}</h1><p>{modo === 'segregar' ? 'La segregación inmoviliza el producto antes de su salida física.' : modo === 'compensar' ? 'La compensación financiera se registra separada de la recepción física del proveedor.' : 'La acción quedará registrada con su versión y responsable.'}</p></div></header>{error && <div className={styles.alertaError}>{error}</div>}{devolucion && !disponible && <div className={styles.alertaAdvertencia}>La devolución está {etiquetaCodigo(devolucion.estado).toLowerCase()} y no admite esta acción.</div>}{devolucion && <form className={styles.formulario} onSubmit={enviar}><section className={styles.resumenDocumento}><div><span>Estado</span><strong>{etiquetaCodigo(devolucion.estado)}</strong></div><div><span>Proveedor</span><strong>{devolucion.proveedor?.nombre}</strong></div><div><span>Ubicación</span><strong>{devolucion.ubicacion?.nombre}</strong></div><div><span>Productos</span><strong>{devolucion.detalles.length}</strong></div></section><fieldset disabled={guardando || !disponible}><legend>{titulos[modo]}</legend>
    {modo === 'autorizar' && <div className={styles.opcionesDecision}><label className={aprobar ? styles.decisionSeleccionada : styles.decision}><input type="radio" checked={aprobar} onChange={() => setAprobar(true)} /><span><strong>{faseProveedor ? 'Proveedor autoriza' : 'Aprobar internamente'}</strong><small>Permite avanzar a la siguiente etapa.</small></span></label><label className={!aprobar ? styles.decisionSeleccionada : styles.decision}><input type="radio" checked={!aprobar} onChange={() => setAprobar(false)} /><span><strong>Rechazar devolución</strong><small>Finaliza el proceso conservando el motivo.</small></span></label></div>}
    {modo === 'autorizar' && faseProveedor && aprobar && <><div className={styles.campo}><label>Referencia de autorización <span>*</span></label><input maxLength={200} value={autorizacion} onChange={(e) => setAutorizacion(e.target.value)} />{errores.autorizacion && <small className={styles.errorCampo}>{errores.autorizacion}</small>}</div><div className={styles.lineasRecepcion}>{devolucion.detalles.map((d) => <article className={styles.lineaRecepcion} key={d.id}><strong>{d.producto?.codigo} — {d.producto?.nombre}</strong><div className={styles.campo}><label>Cantidad autorizada de {n(d.cantidad)}</label><input type="number" min="0" max={n(d.cantidad)} step="0.000001" value={cantidades[d.id] ?? ''} onChange={(e) => setCantidades((a) => ({ ...a, [d.id]: e.target.value }))} /></div></article>)}</div></>}
    {modo === 'recibir' && <><div className={styles.lineasRecepcion}>{devolucion.detalles.map((d) => <article className={styles.lineaRecepcion} key={d.id}><strong>{d.producto?.codigo} — {d.producto?.nombre}</strong><small className={styles.ayudaCampo}>Autorizada: {n(d.cantidadAutorizada)}</small><div className={styles.grillaDos}><div className={styles.campo}><label>Aceptada por proveedor</label><input type="number" min="0" max={n(d.cantidadAutorizada)} step="0.000001" value={cantidades[d.id] ?? ''} onChange={(e) => setCantidades((a) => ({ ...a, [d.id]: e.target.value }))} /></div><div className={styles.campo}><label>Rechazada por proveedor</label><input type="number" min="0" max={n(d.cantidadAutorizada)} step="0.000001" value={rechazadas[d.id] ?? ''} onChange={(e) => setRechazadas((a) => ({ ...a, [d.id]: e.target.value }))} /></div></div></article>)}</div><div className={styles.campo}><label>Evidencia de recepción <span>*</span></label><input maxLength={500} value={evidencia} onChange={(e) => setEvidencia(e.target.value)} />{errores.evidencia && <small className={styles.errorCampo}>{errores.evidencia}</small>}</div></>}
    {modo === 'compensar' && <div className={styles.campo}><label>Referencia de compensación <span>*</span></label><input maxLength={200} value={referencia} onChange={(e) => setReferencia(e.target.value)} />{errores.referencia && <small className={styles.errorCampo}>{errores.referencia}</small>}</div>}
    {['autorizar', 'recibir', 'compensar', 'cerrar', 'cancelar'].includes(modo) && <div className={styles.campo}><label>Motivo <span>*</span></label><textarea rows={5} maxLength={500} value={motivo} onChange={(e) => setMotivo(e.target.value)} />{errores.motivo && <small className={styles.errorCampo}>{errores.motivo}</small>}</div>}{['segregar', 'despachar'].includes(modo) && <div className={styles.alertaAdvertencia}>{modo === 'segregar' ? 'Los productos autorizados pasarán a estado bloqueado y quedarán listos para devolución.' : 'Se registrará la salida física de las cantidades segregadas. Esta acción no registra todavía la compensación.'}</div>}{errores.detalles && <small className={styles.errorCampo}>{errores.detalles}</small>}
  </fieldset><div className={styles.accionesFormulario}><p>* Campos obligatorios</p><div><button className={styles.botonNeutral} type="button" onClick={() => onNavegar(`/abastecimiento/devoluciones/${devolucion.id}`)}><IconoAccion nombre="cancelar" />Volver</button><button className={modo === 'cancelar' || (modo === 'autorizar' && !aprobar) ? styles.botonPeligro : styles.botonPrimario} type="submit" disabled={guardando || !disponible}><IconoAccion nombre="guardar" />{guardando ? 'Procesando…' : titulos[modo]}</button></div></div></form>}</section><ModalEstado abierto={Boolean(guardada)} tipo="exito" titulo="Devolución actualizada" mensaje={guardada ? `La devolución ${guardada.numero} ahora está ${etiquetaCodigo(guardada.estado).toLowerCase()}.` : ''} textoAccionPrincipal="Ver devolución" onAccionPrincipal={() => onNavegar(`/abastecimiento/devoluciones/${devolucionId}`)} onCerrar={() => onNavegar(`/abastecimiento/devoluciones/${devolucionId}`)} /></>
}
