import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ErrorApi } from '../../../shared/api/cliente-api'
import { IconoAccion } from '../../../shared/components/icono-accion'
import { ModalEstado } from '../../../shared/components/modal-estado'
import { SelectorCatalogoBuscable } from '../../../shared/components/selector-catalogo-buscable'
import { crearRegistroAbastecimiento, listarProductosAbastecimiento, listarUbicacionesAbastecimiento, obtenerOpcionesAbastecimiento } from '../abastecimiento-api'
import type { CrearTrasladoInternoRequest, OpcionesFiltrosAbastecimiento, PrioridadTrasladoInterno, ProductoAbastecimiento, TipoTrasladoInterno, TrasladoInterno, UbicacionAbastecimiento } from '../abastecimiento.types'
import { AbastecimientoBreadcrumb } from './abastecimiento-breadcrumb'
import styles from './abastecimiento.module.css'

type Linea = { clave: number; productoId: string; cantidad: string; observaciones: string }
const lineaNueva = (clave: number): Linea => ({ clave, productoId: '', cantidad: '', observaciones: '' })
const hoy = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Guatemala' }).format(new Date())

export function TrasladoCrearView({ sucursalActualId, onNavegar, onCambiosPendientes }: { sucursalActualId: string; onNavegar: (ruta: string) => void; onCambiosPendientes: (pendientes: boolean) => void }) {
  const [opciones, setOpciones] = useState<OpcionesFiltrosAbastecimiento | null>(null)
  const [productos, setProductos] = useState<ProductoAbastecimiento[]>([])
  const [ubicacionesOrigen, setUbicacionesOrigen] = useState<UbicacionAbastecimiento[]>([])
  const [ubicacionesDestino, setUbicacionesDestino] = useState<UbicacionAbastecimiento[]>([])
  const [tipo, setTipo] = useState<TipoTrasladoInterno>('ABASTECIMIENTO')
  const [prioridad, setPrioridad] = useState<PrioridadTrasladoInterno>('NORMAL')
  const [requeridoEn, setRequeridoEn] = useState('')
  const [sucursalOrigenId, setSucursalOrigenId] = useState('')
  const [sucursalDestinoId, setSucursalDestinoId] = useState(sucursalActualId)
  const [ubicacionOrigenId, setUbicacionOrigenId] = useState('')
  const [ubicacionDestinoId, setUbicacionDestinoId] = useState('')
  const [justificacion, setJustificacion] = useState('')
  const [evidencia, setEvidencia] = useState('')
  const [lineas, setLineas] = useState<Linea[]>([lineaNueva(1)])
  const [secuencia, setSecuencia] = useState(2)
  const [errores, setErrores] = useState<Record<string, string>>({})
  const [error, setError] = useState<string | null>(null)
  const [guardando, setGuardando] = useState(false)
  const [guardado, setGuardado] = useState<TrasladoInterno | null>(null)
  const tieneCambios = Boolean(sucursalOrigenId || ubicacionOrigenId || ubicacionDestinoId || requeridoEn || justificacion || evidencia || lineas.some((linea) => linea.productoId || linea.cantidad || linea.observaciones))

  useEffect(() => { const c = new AbortController(); void Promise.all([obtenerOpcionesAbastecimiento(c.signal), listarProductosAbastecimiento('', c.signal)]).then(([o, p]) => { setOpciones(o); setProductos(p) }).catch((e: unknown) => { if (!c.signal.aborted) setError(e instanceof ErrorApi ? e.message : 'No fue posible cargar los catálogos.') }); return () => c.abort() }, [])
  useEffect(() => { if (!sucursalOrigenId) return; const c = new AbortController(); void listarUbicacionesAbastecimiento(sucursalOrigenId, c.signal).then(setUbicacionesOrigen).catch(() => { if (!c.signal.aborted) setError('No fue posible cargar las ubicaciones de origen.') }); return () => c.abort() }, [sucursalOrigenId])
  useEffect(() => { if (!sucursalDestinoId) return; const c = new AbortController(); void listarUbicacionesAbastecimiento(sucursalDestinoId, c.signal).then(setUbicacionesDestino).catch(() => { if (!c.signal.aborted) setError('No fue posible cargar las ubicaciones de destino.') }); return () => c.abort() }, [sucursalDestinoId])
  useEffect(() => onCambiosPendientes(!guardado && tieneCambios), [guardado, onCambiosPendientes, tieneCambios])
  useEffect(() => () => onCambiosPendientes(false), [onCambiosPendientes])
  const productosSeleccionados = useMemo(() => new Set(lineas.map((linea) => linea.productoId).filter(Boolean)), [lineas])

  const enviar = async (evento: FormEvent<HTMLFormElement>) => {
    evento.preventDefault(); const siguientes: Record<string, string> = {}
    if (!sucursalOrigenId) siguientes.sucursalOrigenId = 'Selecciona la sucursal de origen.'
    if (!sucursalDestinoId) siguientes.sucursalDestinoId = 'Selecciona la sucursal de destino.'
    if (sucursalOrigenId && sucursalOrigenId === sucursalDestinoId) siguientes.sucursalDestinoId = 'El origen y el destino deben ser diferentes.'
    if (sucursalOrigenId !== sucursalActualId && sucursalDestinoId !== sucursalActualId) siguientes.sucursalOrigenId = 'La sucursal de sesión debe participar en el traslado.'
    if (!ubicacionOrigenId) siguientes.ubicacionOrigenId = 'Selecciona la ubicación de origen.'
    if (!ubicacionDestinoId) siguientes.ubicacionDestinoId = 'Selecciona la ubicación de destino.'
    if (!requeridoEn || requeridoEn < hoy()) siguientes.requeridoEn = 'Selecciona una fecha vigente.'
    if (justificacion.trim().length < 10 || justificacion.trim().length > 1000) siguientes.justificacion = 'La justificación debe contener de 10 a 1000 caracteres.'
    if (evidencia.trim().length > 500) siguientes.evidencia = 'La referencia admite máximo 500 caracteres.'
    const validas = lineas.filter((linea) => linea.productoId || linea.cantidad || linea.observaciones)
    if (!validas.length) siguientes.detalles = 'Agrega al menos un producto.'
    if (validas.some((linea) => !linea.productoId || !(Number(linea.cantidad) > 0))) siguientes.detalles = 'Completa el producto y una cantidad mayor que cero en cada línea.'
    if (new Set(validas.map((linea) => linea.productoId)).size !== validas.length) siguientes.detalles = 'No repitas productos en la solicitud.'
    setErrores(siguientes); if (Object.keys(siguientes).length) { document.getElementById(`traslado-${Object.keys(siguientes)[0]}`)?.focus(); return }
    const datos: CrearTrasladoInternoRequest = { tipo, prioridad, requeridoEn, sucursalOrigenId, sucursalDestinoId, ubicacionOrigenId, ubicacionDestinoId, justificacion: justificacion.trim(), evidenciaReferencia: evidencia.trim() || null, detalles: validas.map((linea) => ({ productoId: linea.productoId, loteId: null, cantidadSolicitada: Number(linea.cantidad), observaciones: linea.observaciones.trim() || null })) }
    setGuardando(true); setError(null)
    try { setGuardado(await crearRegistroAbastecimiento<TrasladoInterno>('traslados', datos)); onCambiosPendientes(false) } catch (e) { setError(e instanceof ErrorApi ? e.message : 'No fue posible crear el traslado.') } finally { setGuardando(false) }
  }

  return <><section className={styles.pagina} aria-labelledby="titulo-nuevo-traslado"><AbastecimientoBreadcrumb recurso="traslados" actual="Nuevo traslado" onNavegar={onNavegar} /><header className={styles.encabezadoPagina}><div><p className={styles.sobretitulo}>Movimiento entre sucursales</p><h1 id="titulo-nuevo-traslado">Solicitar traslado interno</h1><p>La solicitud reserva trazabilidad, pero no mueve existencias. El lote se confirma durante la preparación en la sucursal de origen.</p></div></header>{error && <div className={styles.alertaError} role="alert">{error}</div>}<form className={styles.formulario} noValidate onSubmit={enviar}>
    <fieldset disabled={guardando}><legend>Ruta y prioridad</legend><div className={styles.grillaTres}><div className={styles.campo}><label htmlFor="traslado-tipo">Tipo <span>*</span></label><select id="traslado-tipo" value={tipo} onChange={(e) => setTipo(e.target.value as TipoTrasladoInterno)}><option value="ABASTECIMIENTO">Abastecimiento</option><option value="DEVOLUCION_INTERNA">Devolución interna</option><option value="TRASLADO_HORIZONTAL">Traslado horizontal</option><option value="REDISTRIBUCION">Redistribución</option></select></div><div className={styles.campo}><label htmlFor="traslado-prioridad">Prioridad <span>*</span></label><select id="traslado-prioridad" value={prioridad} onChange={(e) => setPrioridad(e.target.value as PrioridadTrasladoInterno)}><option value="NORMAL">Normal</option><option value="ALTA">Alta</option><option value="EMERGENCIA">Emergencia</option></select></div><div className={styles.campo}><label htmlFor="traslado-requeridoEn">Requerido para <span>*</span></label><input id="traslado-requeridoEn" type="date" min={hoy()} value={requeridoEn} aria-invalid={Boolean(errores.requeridoEn)} onChange={(e) => setRequeridoEn(e.target.value)} />{errores.requeridoEn && <small className={styles.errorCampo}>{errores.requeridoEn}</small>}</div></div>
    <div className={styles.grillaDos}><div className={styles.campo}><label htmlFor="traslado-sucursalOrigenId">Sucursal origen <span>*</span></label><SelectorCatalogoBuscable id="traslado-sucursalOrigenId" valor={sucursalOrigenId} opciones={(opciones?.sucursalesTraslado ?? []).map((x) => ({ valor: x.id, etiqueta: `${x.codigo} — ${x.nombre}` }))} placeholder="Selecciona el origen" invalido={Boolean(errores.sucursalOrigenId)} onChange={(v) => { setSucursalOrigenId(v); setUbicacionOrigenId('') }} />{errores.sucursalOrigenId && <small className={styles.errorCampo}>{errores.sucursalOrigenId}</small>}</div><div className={styles.campo}><label htmlFor="traslado-ubicacionOrigenId">Ubicación origen <span>*</span></label><select id="traslado-ubicacionOrigenId" value={ubicacionOrigenId} aria-invalid={Boolean(errores.ubicacionOrigenId)} onChange={(e) => setUbicacionOrigenId(e.target.value)}><option value="">Selecciona una ubicación</option>{ubicacionesOrigen.filter((x) => x.activa !== false && !x.bloqueada).map((x) => <option key={x.id} value={x.id}>{x.codigo} — {x.nombre}</option>)}</select>{errores.ubicacionOrigenId && <small className={styles.errorCampo}>{errores.ubicacionOrigenId}</small>}</div><div className={styles.campo}><label htmlFor="traslado-sucursalDestinoId">Sucursal destino <span>*</span></label><SelectorCatalogoBuscable id="traslado-sucursalDestinoId" valor={sucursalDestinoId} opciones={(opciones?.sucursalesTraslado ?? []).map((x) => ({ valor: x.id, etiqueta: `${x.codigo} — ${x.nombre}` }))} placeholder="Selecciona el destino" invalido={Boolean(errores.sucursalDestinoId)} onChange={(v) => { setSucursalDestinoId(v); setUbicacionDestinoId('') }} />{errores.sucursalDestinoId && <small className={styles.errorCampo}>{errores.sucursalDestinoId}</small>}</div><div className={styles.campo}><label htmlFor="traslado-ubicacionDestinoId">Ubicación destino <span>*</span></label><select id="traslado-ubicacionDestinoId" value={ubicacionDestinoId} aria-invalid={Boolean(errores.ubicacionDestinoId)} onChange={(e) => setUbicacionDestinoId(e.target.value)}><option value="">Selecciona una ubicación</option>{ubicacionesDestino.filter((x) => x.activa !== false && !x.bloqueada).map((x) => <option key={x.id} value={x.id}>{x.codigo} — {x.nombre}</option>)}</select>{errores.ubicacionDestinoId && <small className={styles.errorCampo}>{errores.ubicacionDestinoId}</small>}</div></div></fieldset>
    <fieldset disabled={guardando}><legend>Productos solicitados</legend><div className={styles.lineasProductos}>{lineas.map((linea, indice) => <div className={styles.lineaProducto} key={linea.clave}><span className={styles.numeroLinea}>{indice + 1}</span><div className={styles.campoProducto}><label htmlFor={`traslado-producto-${linea.clave}`}>Producto</label><SelectorCatalogoBuscable id={`traslado-producto-${linea.clave}`} valor={linea.productoId} opciones={productos.filter((p) => p.id === linea.productoId || !productosSeleccionados.has(p.id)).map((p) => ({ valor: p.id, etiqueta: `${p.codigo} — ${p.nombre}` }))} placeholder="Selecciona un producto" onChange={(v) => setLineas((a) => a.map((x) => x.clave === linea.clave ? { ...x, productoId: v } : x))} /></div><div className={styles.campo}><label htmlFor={`traslado-cantidad-${linea.clave}`}>Cantidad</label><input id={`traslado-cantidad-${linea.clave}`} type="number" min="0.000001" step="0.000001" value={linea.cantidad} onChange={(e) => setLineas((a) => a.map((x) => x.clave === linea.clave ? { ...x, cantidad: e.target.value } : x))} /></div><div className={styles.campo}><label htmlFor={`traslado-observacion-${linea.clave}`}>Observaciones</label><input id={`traslado-observacion-${linea.clave}`} maxLength={500} value={linea.observaciones} onChange={(e) => setLineas((a) => a.map((x) => x.clave === linea.clave ? { ...x, observaciones: e.target.value } : x))} /></div><button className={styles.botonQuitarLinea} type="button" aria-label={`Quitar producto ${indice + 1}`} disabled={lineas.length === 1} onClick={() => setLineas((a) => a.filter((x) => x.clave !== linea.clave))}>×</button></div>)}</div>{errores.detalles && <small className={styles.errorCampo}>{errores.detalles}</small>}<button className={`${styles.botonSecundario} ${styles.botonAgregarLinea}`} type="button" onClick={() => { setLineas((a) => [...a, lineaNueva(secuencia)]); setSecuencia((v) => v + 1) }}><IconoAccion nombre="agregar" />Agregar producto</button></fieldset>
    <fieldset disabled={guardando}><legend>Justificación y evidencia</legend><div className={styles.campo}><label htmlFor="traslado-justificacion">Justificación <span>*</span></label><textarea id="traslado-justificacion" rows={5} maxLength={1000} value={justificacion} aria-invalid={Boolean(errores.justificacion)} onChange={(e) => setJustificacion(e.target.value)} />{errores.justificacion && <small className={styles.errorCampo}>{errores.justificacion}</small>}</div><div className={styles.campo}><label htmlFor="traslado-evidencia">Referencia de evidencia</label><input id="traslado-evidencia" maxLength={500} value={evidencia} onChange={(e) => setEvidencia(e.target.value)} />{errores.evidencia && <small className={styles.errorCampo}>{errores.evidencia}</small>}</div></fieldset>
    <div className={styles.accionesFormulario}><p><span>*</span> Campos obligatorios</p><div><button className={styles.botonNeutral} type="button" onClick={() => onNavegar('/abastecimiento/traslados')}><IconoAccion nombre="cancelar" />Volver sin guardar</button><button className={styles.botonPrimario} type="submit" disabled={guardando}><IconoAccion nombre="guardar" />{guardando ? 'Guardando…' : 'Crear traslado'}</button></div></div>
  </form></section><ModalEstado abierto={Boolean(guardado)} tipo="exito" titulo="Traslado solicitado" mensaje={guardado ? `El traslado ${guardado.numero} quedó registrado sin afectar existencias.` : ''} textoAccionPrincipal="Ver traslado" onAccionPrincipal={() => onNavegar(`/abastecimiento/traslados/${guardado?.id}`)} onCerrar={() => onNavegar(`/abastecimiento/traslados/${guardado?.id}`)} /></>
}
