import type { OpcionesProducto } from '../producto.types'
import type { DatosProducto, ErroresProducto } from '../validacion-producto'
import { SelectorCatalogoBuscable } from '../../../shared/components/selector-catalogo-buscable'
import styles from '../../roles/components/rol-formulario.module.css'
type Props = { datos: DatosProducto; errores: ErroresProducto; opciones: OpcionesProducto; deshabilitado: boolean; onChange: (datos: DatosProducto) => void }
export function ProductoFormularioCampos({ datos, errores, opciones, deshabilitado, onChange }: Props) {
  const cambiar = <K extends keyof DatosProducto>(campo: K, valor: DatosProducto[K]) => onChange({ ...datos, [campo]: valor })
  const activos = <T extends { activo: boolean }>(items: T[]) => items.filter((item) => item.activo)
  return <fieldset disabled={deshabilitado}><legend>Identificación del medicamento</legend><div className={styles.grillaDos}>
    <div className={styles.campo}><label htmlFor="codigo">Código interno <span aria-hidden="true">*</span></label><input id="codigo" value={datos.codigo} maxLength={30} onChange={(e) => cambiar('codigo', e.target.value.toUpperCase())} aria-invalid={Boolean(errores.codigo)} />{errores.codigo && <small className={styles.errorCampo}>{errores.codigo}</small>}</div>
    <div className={styles.campo}><label htmlFor="nombreComercial">Nombre comercial <span aria-hidden="true">*</span></label><input id="nombreComercial" value={datos.nombreComercial} maxLength={200} onChange={(e) => cambiar('nombreComercial', e.target.value)} aria-invalid={Boolean(errores.nombreComercial)} />{errores.nombreComercial && <small className={styles.errorCampo}>{errores.nombreComercial}</small>}</div>
    <div className={styles.campo}><label htmlFor="laboratorioId">Laboratorio <span aria-hidden="true">*</span></label><SelectorCatalogoBuscable id="laboratorioId" valor={datos.laboratorioId} opciones={activos(opciones.laboratorios).map((x) => ({ valor: x.id, etiqueta: `${x.codigo} — ${x.nombre}` }))} placeholder="Selecciona un laboratorio" deshabilitado={deshabilitado} invalido={Boolean(errores.laboratorioId)} onChange={(valor) => cambiar('laboratorioId', valor)} />{errores.laboratorioId && <small className={styles.errorCampo}>{errores.laboratorioId}</small>}</div>
    <div className={styles.campo}><label htmlFor="presentacionId">Presentación <span aria-hidden="true">*</span></label><SelectorCatalogoBuscable id="presentacionId" valor={datos.presentacionId} opciones={activos(opciones.presentaciones).map((x) => ({ valor: x.id, etiqueta: x.nombre }))} placeholder="Selecciona una presentación" deshabilitado={deshabilitado} invalido={Boolean(errores.presentacionId)} onChange={(valor) => cambiar('presentacionId', valor)} />{errores.presentacionId && <small className={styles.errorCampo}>{errores.presentacionId}</small>}</div>
    <div className={styles.campo}><label htmlFor="formaFarmaceuticaId">Forma farmacéutica <span aria-hidden="true">*</span></label><SelectorCatalogoBuscable id="formaFarmaceuticaId" valor={datos.formaFarmaceuticaId} opciones={activos(opciones.formasFarmaceuticas).map((x) => ({ valor: x.id, etiqueta: x.nombre }))} placeholder="Selecciona una forma" deshabilitado={deshabilitado} invalido={Boolean(errores.formaFarmaceuticaId)} onChange={(valor) => cambiar('formaFarmaceuticaId', valor)} />{errores.formaFarmaceuticaId && <small className={styles.errorCampo}>{errores.formaFarmaceuticaId}</small>}</div>
    <div className={styles.campo}><label htmlFor="categoriaTerapeuticaIds">Categorías terapéuticas <span aria-hidden="true">*</span></label><SelectorCatalogoBuscable id="categoriaTerapeuticaIds" multiple valor={datos.categoriaTerapeuticaIds} opciones={activos(opciones.categoriasTerapeuticas).map((x) => ({ valor: x.id, etiqueta: x.nombre }))} placeholder="Selecciona categorías" deshabilitado={deshabilitado} invalido={Boolean(errores.categoriaTerapeuticaIds)} onChange={(valor) => cambiar('categoriaTerapeuticaIds', valor)} /><small>Puede seleccionar más de una opción.</small>{errores.categoriaTerapeuticaIds && <small className={styles.errorCampo}>{errores.categoriaTerapeuticaIds}</small>}</div>
    <div className={styles.campo}><label htmlFor="viaAdministracionIds">Vías de administración <span aria-hidden="true">*</span></label><SelectorCatalogoBuscable id="viaAdministracionIds" multiple valor={datos.viaAdministracionIds} opciones={activos(opciones.viasAdministracion).map((x) => ({ valor: x.id, etiqueta: x.nombre }))} placeholder="Selecciona vías de administración" deshabilitado={deshabilitado} invalido={Boolean(errores.viaAdministracionIds)} onChange={(valor) => cambiar('viaAdministracionIds', valor)} /><small>Puede seleccionar más de una opción.</small>{errores.viaAdministracionIds && <small className={styles.errorCampo}>{errores.viaAdministracionIds}</small>}</div>
    <div className={styles.campo}><label htmlFor="cantidadContenido">Cantidad contenida <span aria-hidden="true">*</span></label><input id="cantidadContenido" type="number" min="0.000001" step="any" value={datos.cantidadContenido} onChange={(e) => cambiar('cantidadContenido', e.target.value)} aria-invalid={Boolean(errores.cantidadContenido)} />{errores.cantidadContenido && <small className={styles.errorCampo}>{errores.cantidadContenido}</small>}</div>
    <div className={styles.campo}><label htmlFor="unidadContenidoId">Unidad de contenido <span aria-hidden="true">*</span></label><SelectorCatalogoBuscable id="unidadContenidoId" valor={datos.unidadContenidoId} opciones={activos(opciones.unidadesMedida).map((x) => ({ valor: x.id, etiqueta: `${x.nombre}${x.simbolo ? ` (${x.simbolo})` : ''}` }))} placeholder="Selecciona una unidad" deshabilitado={deshabilitado} invalido={Boolean(errores.unidadContenidoId)} onChange={(valor) => cambiar('unidadContenidoId', valor)} />{errores.unidadContenidoId && <small className={styles.errorCampo}>{errores.unidadContenidoId}</small>}</div>
  </div><div className={styles.campo}><label htmlFor="condicionesAlmacenamiento">Condiciones de almacenamiento</label><textarea id="condicionesAlmacenamiento" rows={3} maxLength={500} value={datos.condicionesAlmacenamiento ?? ''} onChange={(e) => cambiar('condicionesAlmacenamiento', e.target.value)} /></div>
  <legend>Controles farmacéuticos</legend><div className={styles.grillaDos}>
    <label><input type="checkbox" checked={datos.requiereReceta} onChange={(e) => cambiar('requiereReceta', e.target.checked)} /> Requiere receta</label>
    <label><input type="checkbox" checked={datos.esControlado} onChange={(e) => cambiar('esControlado', e.target.checked)} /> Medicamento controlado</label>
    <label><input type="checkbox" checked={datos.controlaLote} onChange={(e) => cambiar('controlaLote', e.target.checked)} /> Controla lote</label>
    <label><input type="checkbox" checked={datos.requiereVencimiento} onChange={(e) => cambiar('requiereVencimiento', e.target.checked)} /> Requiere fecha de vencimiento</label>
  </div>{errores.requiereReceta && <small className={styles.errorCampo}>{errores.requiereReceta}</small>}
  <legend>Composición</legend>{datos.componentes.map((item, indice) => <div className={styles.grillaDos} key={`${indice}-${item.principioActivoId}`}>
    <div className={styles.campo}><label htmlFor={`principio-${indice}`}>Principio activo <span aria-hidden="true">*</span></label><SelectorCatalogoBuscable id={`principio-${indice}`} valor={item.principioActivoId} opciones={activos(opciones.principiosActivos).map((x) => ({ valor: x.id, etiqueta: x.nombre }))} placeholder="Selecciona un principio" deshabilitado={deshabilitado} onChange={(valor) => cambiar('componentes', datos.componentes.map((x, i) => i === indice ? { ...x, principioActivoId: valor } : x))} /></div>
    <div className={styles.campo}><label htmlFor={`concentracion-${indice}`}>Concentración y unidad <span aria-hidden="true">*</span></label><div><input id={`concentracion-${indice}`} type="number" min="0.000001" step="any" value={item.concentracion} onChange={(e) => cambiar('componentes', datos.componentes.map((x, i) => i === indice ? { ...x, concentracion: e.target.value } : x))} /><SelectorCatalogoBuscable id={`unidad-concentracion-${indice}`} valor={item.unidadMedidaId} opciones={activos(opciones.unidadesMedida).map((x) => ({ valor: x.id, etiqueta: x.simbolo ?? x.nombre }))} placeholder="Unidad" deshabilitado={deshabilitado} onChange={(valor) => cambiar('componentes', datos.componentes.map((x, i) => i === indice ? { ...x, unidadMedidaId: valor } : x))} />{datos.componentes.length > 1 && <button type="button" onClick={() => cambiar('componentes', datos.componentes.filter((_, i) => i !== indice))}>Quitar</button>}</div></div>
  </div>)}{errores.componentes && <small className={styles.errorCampo}>{errores.componentes}</small>}<button className={styles.botonSecundario} type="button" onClick={() => cambiar('componentes', [...datos.componentes, { principioActivoId: '', concentracion: '', unidadMedidaId: '' }])}>Agregar principio activo</button>
  <legend>Códigos de barras</legend>{datos.codigosBarras.map((item, indice) => <div className={styles.grillaDos} key={indice}><div className={styles.campo}><label htmlFor={`barra-${indice}`}>Código de barras {indice + 1}</label><input id={`barra-${indice}`} inputMode="numeric" maxLength={30} value={item.codigo} onChange={(e) => cambiar('codigosBarras', datos.codigosBarras.map((x, i) => i === indice ? { ...x, codigo: e.target.value.replace(/\D/g, '') } : x))} /></div><div><label><input type="radio" name="codigo-principal" checked={item.esPrincipal} onChange={() => cambiar('codigosBarras', datos.codigosBarras.map((x, i) => ({ ...x, esPrincipal: i === indice })))} /> Principal</label>{datos.codigosBarras.length > 1 && <button type="button" onClick={() => { const restantes = datos.codigosBarras.filter((_, i) => i !== indice); if (item.esPrincipal && restantes[0]) restantes[0].esPrincipal = true; cambiar('codigosBarras', restantes) }}>Quitar</button>}</div></div>)}{errores.codigosBarras && <small className={styles.errorCampo}>{errores.codigosBarras}</small>}<button className={styles.botonSecundario} type="button" onClick={() => cambiar('codigosBarras', [...datos.codigosBarras, { codigo: '', esPrincipal: false }])}>Agregar código de barras</button>
  </fieldset>
}
